"use client";

import { useState } from "react";

const copy = {
  "zh-CN": {nav:["返佣方案","收益测算","市场简报","如何开始"], badge:"透明费率 · 非托管 · 每日更新", title:"把每一笔交易成本，\n变成可见的返还。", sub:"连接主流交易所专属通道，最高返还 75% 渠道佣金。无需 API Key，不接触你的资产。", cta:"查看返佣方案", brief:"今日市场简报", volume:"月合约交易量", rate:"返佣比例", result:"预计每月返还", steps:"三步开始返佣", faq:"常见问题"},
  "zh-TW": {nav:["返佣方案","收益試算","市場簡報","如何開始"], badge:"透明費率 · 非託管 · 每日更新", title:"把每一筆交易成本，\n變成可見的返還。", sub:"連接主流交易所專屬通道，最高返還 75% 渠道佣金。無需 API Key，不接觸你的資產。", cta:"查看返佣方案", brief:"今日市場簡報", volume:"月合約交易量", rate:"返佣比例", result:"預計每月返還", steps:"三步開始返佣", faq:"常見問題"},
  en: {nav:["Rebates","Calculator","Market Brief","How it works"], badge:"Transparent · Non-custodial · Updated daily", title:"Turn every trading cost\ninto a visible rebate.", sub:"Access partner channels across leading exchanges and receive up to 75% of affiliate commissions. No API keys. We never touch your assets.", cta:"Explore rebates", brief:"Today’s market brief", volume:"Monthly futures volume", rate:"Rebate rate", result:"Estimated monthly rebate", steps:"Start in three steps", faq:"Questions"}
};
const exchanges=[{n:"Gate",r:75,f:.05},{n:"Bybit",r:65,f:.055},{n:"Bitget",r:60,f:.06},{n:"OKX",r:50,f:.05},{n:"MEXC",r:65,f:.04},{n:"Binance",r:45,f:.05}];
export default function Home(){
 const [lang,setLang]=useState<keyof typeof copy>("zh-CN"),[ex,setEx]=useState(0),[vol,setVol]=useState(1000000); const t=copy[lang], e=exchanges[ex], rebate=vol*e.f/100*e.r/100;
 return <main><header><a className="brand" href="#"><i>R</i> REBATE<span>ONE</span></a><nav>{t.nav.map((x,i)=><a key={x} href={i===2?"/brief":"#"+(i===0?"rates":i===1?"calculator":"steps")}>{x}</a>)}</nav><select aria-label="Language" value={lang} onChange={x=>setLang(x.target.value as keyof typeof copy)}><option value="zh-CN">简体中文</option><option value="zh-TW">繁體中文</option><option value="en">English</option></select></header>
 <section className="hero"><div className="heroCopy"><p className="badge">● {t.badge}</p><h1>{t.title}</h1><p className="lead">{t.sub}</p><div className="actions"><a className="primary" href="#rates">{t.cta} →</a><a className="secondary" href="/brief">{t.brief}</a></div><div className="proof"><b>10+</b> exchanges <b>$18.6M</b> tracked volume <b>24h</b> reconciliation</div></div><div className="terminal"><div className="termTop"><span>REBATE STREAM</span><em>● LIVE</em></div>{exchanges.slice(0,5).map((x,i)=><div className="tick" key={x.n}><b>{x.n}</b><small>TRADING FEE</small><span>${[182.4,96.2,241.8,75.6,134.2][i].toFixed(2)}</span><strong>+${([182.4,96.2,241.8,75.6,134.2][i]*x.r/100).toFixed(2)}</strong></div>)}<div className="termFoot"><span>TODAY RETURNED</span><b>$48,213.57</b></div></div></section>
 <section id="rates" className="section"><p className="eyebrow">PARTNER NETWORK</p><h2>更低净费率，从清晰的数字开始</h2><div className="cards">{exchanges.map(x=><article key={x.n}><div className="exchange"><i>{x.n[0]}</i><b>{x.n}</b><span>DERIVATIVES</span></div><p>渠道返佣</p><h3>{x.r}%</h3><div className="metric"><span>Taker 基础费率</span><b>{x.f.toFixed(3)}%</b></div><div className="metric"><span>返佣后净费率</span><b>≈ {(x.f*(1-x.r/100)).toFixed(3)}%</b></div><button>查看开户指引 →</button></article>)}</div><p className="disclaimer">费率与资格因地区、账户状态及交易所政策而异，最终以交易所官方页面和账户显示为准。</p></section>
 <section id="calculator" className="calcWrap"><div><p className="eyebrow">REBATE CALCULATOR</p><h2>30 秒估算你的返佣</h2><p className="muted">使用公开基础费率进行估算，实际金额以交易所结算为准。</p></div><div className="calculator"><label>Exchange<select value={ex} onChange={x=>setEx(+x.target.value)}>{exchanges.map((x,i)=><option value={i} key={x.n}>{x.n}</option>)}</select></label><label>{t.volume}<strong>${vol.toLocaleString()}</strong><input type="range" min="100000" max="10000000" step="100000" value={vol} onChange={x=>setVol(+x.target.value)}/></label><div className="calcResult"><span>{t.result}</span><b>${rebate.toLocaleString(undefined,{maximumFractionDigits:2})}</b><small>{t.rate} {e.r}% · Taker {e.f}%</small></div></div></section>
 <section className="briefBand"><div><p className="eyebrow">DAILY INTELLIGENCE · 11 JUL 2026</p><h2>市场噪音很多，重点只有几个。</h2><p>每日追踪 BTC、ETH、资金流、宏观事件与关键风险位，用 3 分钟完成盘前准备。</p></div><a href="/brief">阅读今日简报 →</a></section>
 <section id="steps" className="section"><p className="eyebrow">HOW IT WORKS</p><h2>{t.steps}</h2><div className="steps">{[["01","选择交易所","比较返佣比例、费率与开户条件。"],["02","通过专属链接注册","确认邀请码已正确绑定，全程无需 API Key。"],["03","交易并获得返还","系统定期对账，符合条件的返佣按规则发放。"]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <footer><a className="brand" href="#"><i>R</i> REBATE<span>ONE</span></a><p>信息仅供参考，不构成投资建议。数字资产交易具有高风险。</p><span>© 2026 RebateOne</span></footer></main>
}
