"use client";

import { useEffect, useMemo, useState } from "react";
import { Brand, ExchangeLogo } from "./brand";

const copy = {
  "zh-CN": {nav:["返佣方案","收益测算","市场简报","如何开始"], badge:"透明费率 · 非托管 · 每日更新", title:"把每一笔交易成本，\n变成可见的返还。", sub:"连接主流交易所专属通道，最高返还 90% 渠道佣金。无需 API Key，不接触你的资产。", cta:"查看返佣方案", brief:"今日市场简报", volume:"月合约交易量", rate:"返佣比例", result:"预计每月返还", steps:"三步开始返佣", faq:"常见问题"},
  "zh-TW": {nav:["返佣方案","收益試算","市場簡報","如何開始"], badge:"透明費率 · 非託管 · 每日更新", title:"把每一筆交易成本，\n變成可見的返還。", sub:"連接主流交易所專屬通道，最高返還 90% 渠道佣金。無需 API Key，不接觸你的資產。", cta:"查看返佣方案", brief:"今日市場簡報", volume:"月合約交易量", rate:"返佣比例", result:"預計每月返還", steps:"三步開始返佣", faq:"常見問題"},
  en: {nav:["Rebates","Calculator","Market Brief","How it works"], badge:"Transparent · Non-custodial · Updated daily", title:"Turn every trading cost\ninto a visible rebate.", sub:"Access partner channels across leading exchanges and receive up to 90% of affiliate commissions. No API keys. We never touch your assets.", cta:"Explore rebates", brief:"Today’s market brief", volume:"Monthly futures volume", rate:"Rebate rate", result:"Estimated monthly rebate", steps:"Start in three steps", faq:"Questions"}
};
const exchanges=[
 {n:"Binance",r:20,rEn:45,maker:.020,taker:.050,code:"TOPCODE",urlZh:"https://www.bsmkweb.cc/register?ref=TOPCODE",urlGlobal:"https://www.binance.com/zh-CN/join?ref=TOPCODE"},
 {n:"Gate",r:75,maker:.020,taker:.050,code:"VLYQB1HXUW",url:"https://www.gate.com/signup/VLYQB1HXUW"},
 {n:"Hyperliquid",r:20,maker:.015,taker:.045,code:"HLBESTCODE",url:"https://app.hyperliquid.xyz/join/HLBESTCODE"},
 {n:"OKX",r:20,maker:.020,taker:.050,code:"Bestcode",url:"https://www.okx.com/join/Bestcode"},
 {n:"MEXC",r:70,maker:.000,taker:.020,code:"Bestcode",url:"https://www.mexc.com/register?inviteCode=Bestcode"},
 {n:"BitMart",r:90,maker:.020,taker:.060,code:"ctWMTf",url:"https://www.bitmart.com/register-referral/en?r=ctWMTf"}
];
export default function Home(){
 const [lang,setLang]=useState<keyof typeof copy>("zh-CN"),[ex,setEx]=useState(0),[vol,setVol]=useState(1000000),[orderType,setOrderType]=useState<"taker"|"maker">("taker"),[streamTotal,setStreamTotal]=useState(0),[copied,setCopied]=useState(""); const t=copy[lang], e=exchanges[ex], rebateRate=(x:typeof exchanges[number])=>x.n==="Binance"&&lang==="en"?45:x.r, eRate=rebateRate(e), feeRate=e[orderType], monthlyFee=vol*feeRate/100, rebate=monthlyFee*eRate/100, annualRebate=rebate*12,netRate=feeRate*(1-eRate/100); const openExchange=async(x:typeof exchanges[number])=>{try{await navigator.clipboard.writeText(x.code);setCopied(x.n)}catch{}const url=x.n==="Binance"?(lang==="zh-CN"?x.urlZh:x.urlGlobal):x.url;window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>setCopied(""),1800)};
 useEffect(()=>{const update=()=>{const now=new Date(),dayStart=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),progress=Math.min(1,(now.getTime()-dayStart)/86400000);setStreamTotal(800*progress)};update();const timer=setInterval(update,10000);return()=>clearInterval(timer)},[]);
 const stream=useMemo(()=>{const seed=new Date().toISOString().slice(0,10).split("").reduce((a,c)=>a+c.charCodeAt(0),0),weights=exchanges.map((_,i)=>.65+((seed*(i+3)*17)%63)/100),sum=weights.reduce((a,b)=>a+b,0);return weights.map(x=>streamTotal*x/sum)},[streamTotal]);
 return <main className="siteShell"><div className="ambient" aria-hidden="true"><i/><i/><i/><i/></div><header><a className="brand" href="#"><Brand/></a><nav>{t.nav.map((x,i)=><a key={x} href={i===2?"/brief":"#"+(i===0?"rates":i===1?"calculator":"steps")}>{x}</a>)}</nav><select aria-label="Language" value={lang} onChange={x=>setLang(x.target.value as keyof typeof copy)}><option value="zh-CN">简体中文</option><option value="zh-TW">繁體中文</option><option value="en">English</option></select></header>
 <section className="hero"><div className="heroCopy"><p className="badge">● {t.badge}</p><h1>{t.title}</h1><p className="lead">{t.sub}</p><div className="actions"><a className="primary" href="#rates">{t.cta} →</a><a className="secondary" href="/brief">{t.brief}</a></div><div className="proof"><b>{exchanges.length}</b> exchanges <b>VIP 0</b> official fee tiers <b>Daily</b> reconciliation</div></div><div className="terminal"><div className="termTop"><span>REBATE CASE STUDY</span><em>● ESTIMATED</em></div>{exchanges.map((x,i)=><div className="tick" key={x.n}><b>{x.n}</b><small>DAILY ALLOCATION</small><span>{rebateRate(x)}% rebate</span><strong>+${stream[i].toFixed(2)}</strong></div>)}<div className="termFoot"><span>ESTIMATED TODAY <small>示例目标约 $800 / 日</small></span><b>${streamTotal.toFixed(2)}</b></div></div></section>
 <section id="rates" className="section"><p className="eyebrow">PARTNER NETWORK</p><h2>更低净费率，从清晰的数字开始</h2><div className="cards">{exchanges.map(x=><article key={x.n}><div className="exchange"><i><ExchangeLogo name={x.n}/></i><b>{x.n}</b><span>DERIVATIVES · LOWEST TIER</span></div><p>渠道返佣</p><h3>{rebateRate(x)}%</h3><div className="metric"><span>Maker / Taker</span><b>{x.maker.toFixed(3)}% / {x.taker.toFixed(3)}%</b></div><div className="metric"><span>Taker 返佣后净费率</span><b>≈ {(x.taker*(1-rebateRate(x)/100)).toFixed(3)}%</b></div><div className="invite"><span>邀请码</span><strong>{x.code}</strong></div><button type="button" onClick={()=>openExchange(x)}>{copied===x.n?"邀请码已复制 ✓":"复制邀请码 · 开户 →"}</button></article>)}</div><p className="disclaimer">费率按各交易所合约/永续最低普通等级公开标准测算。地区、交易对、活动、账户等级及平台政策可能改变实际费率，最终以交易所账户显示为准。</p></section>
 <section id="calculator" className="calcWrap"><div className="calcIntro"><p className="eyebrow">30 秒测算</p><h2>你每月能返多少？拖一下就知道</h2></div><p className="calcLead">选择交易所、订单类型并拖动月交易量，按照最低普通等级公开费率实时计算。</p><div className="calculator"><div className="calcBar"><span><i/>返佣测算台</span><b>VIP 0 · LIVE ESTIMATE</b></div><div className="calcControls"><label>选择交易所<div className="exchangePills">{exchanges.map((x,i)=><button type="button" className={ex===i?"active":""} onClick={()=>setEx(i)} key={x.n}><ExchangeLogo name={x.n}/>{x.n}</button>)}</div></label><label>{t.volume}<strong>${vol.toLocaleString()}</strong><input type="range" min="100000" max="10000000" step="1000" value={vol} onChange={x=>setVol(+x.target.value)}/><div className="quickVolumes"><button onClick={()=>setVol(100000)}>$100K</button><button onClick={()=>setVol(1000000)}>$1M</button><button onClick={()=>setVol(10000000)}>$10M</button></div></label><div className="orderType"><button type="button" className={orderType==="taker"?"active":""} onClick={()=>setOrderType("taker")}>Taker 吃单&nbsp; {e.taker.toFixed(3)}%</button><button type="button" className={orderType==="maker"?"active":""} onClick={()=>setOrderType("maker")}>Maker 挂单&nbsp; {e.maker.toFixed(3)}%</button></div></div><div className="calcOutput"><span>{t.result}</span><b>${rebate.toLocaleString(undefined,{maximumFractionDigits:2})}</b><small>≈ ${annualRebate.toLocaleString(undefined,{maximumFractionDigits:2})} / 年</small><div className="feeRow"><span>月手续费</span><strong>${monthlyFee.toLocaleString(undefined,{maximumFractionDigits:2})}</strong></div><div className="feeTrack"><i style={{width:`${eRate}%`}}/></div><p>● 返还 {eRate}% · ${rebate.toLocaleString(undefined,{maximumFractionDigits:2})}<em>净付 ${(monthlyFee-rebate).toLocaleString(undefined,{maximumFractionDigits:2})}</em></p><div className="rateCompare"><span>原始费率<del>{feeRate.toFixed(3)}%</del></span><span>返佣后净费率<b>{netRate.toFixed(3)}%</b></span></div></div></div></section>
 <section className="briefBand"><div><p className="eyebrow">DAILY INTELLIGENCE · 22 JUL 2026</p><h2>AI 硬件反弹，Alphabet 接受资本回报检验。</h2><p>存储链成交回暖、台湾市场板块轮动；高油价与美债收益率仍约束科技估值。</p></div><a href="/brief/2026-07-22">阅读今日简报 →</a></section>
 <section id="steps" className="section"><p className="eyebrow">HOW IT WORKS</p><h2>{t.steps}</h2><div className="steps">{[["01","选择交易所","比较返佣比例、费率与开户条件。"],["02","通过专属链接注册","确认邀请码已正确绑定，全程无需 API Key。"],["03","交易并获得返还","系统定期对账，符合条件的返佣按规则发放。"]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <footer><a className="brand" href="#"><Brand/></a><p>信息仅供参考，不构成投资建议。数字资产交易具有高风险。</p><span>© 2026 CryptoBonusCodeHub.com</span></footer></main>
}
