"use client";

import { useEffect, useMemo, useState } from "react";

const copy = {
  "zh-CN": {nav:["返佣方案","收益测算","市场简报","如何开始"], badge:"透明费率 · 非托管 · 每日更新", title:"把每一笔交易成本，\n变成可见的返还。", sub:"连接主流交易所专属通道，最高返还 75% 渠道佣金。无需 API Key，不接触你的资产。", cta:"查看返佣方案", brief:"今日市场简报", volume:"月合约交易量", rate:"返佣比例", result:"预计每月返还", steps:"三步开始返佣", faq:"常见问题"},
  "zh-TW": {nav:["返佣方案","收益試算","市場簡報","如何開始"], badge:"透明費率 · 非託管 · 每日更新", title:"把每一筆交易成本，\n變成可見的返還。", sub:"連接主流交易所專屬通道，最高返還 75% 渠道佣金。無需 API Key，不接觸你的資產。", cta:"查看返佣方案", brief:"今日市場簡報", volume:"月合約交易量", rate:"返佣比例", result:"預計每月返還", steps:"三步開始返佣", faq:"常見問題"},
  en: {nav:["Rebates","Calculator","Market Brief","How it works"], badge:"Transparent · Non-custodial · Updated daily", title:"Turn every trading cost\ninto a visible rebate.", sub:"Access partner channels across leading exchanges and receive up to 75% of affiliate commissions. No API keys. We never touch your assets.", cta:"Explore rebates", brief:"Today’s market brief", volume:"Monthly futures volume", rate:"Rebate rate", result:"Estimated monthly rebate", steps:"Start in three steps", faq:"Questions"}
};
const exchanges=[
 {n:"Gate",r:75,f:.04,code:"VLYQB1HXUW"},
 {n:"Hyperliquid",r:20,f:.04,code:"HLBESTCODE"},
 {n:"OKX",r:20,f:.04,code:"Bestcode"},
 {n:"MEXC",r:70,f:.04,code:"Bestcode"},
 {n:"BitMart",r:90,f:.04,code:"ctWMTf"}
];
export default function Home(){
 const [lang,setLang]=useState<keyof typeof copy>("zh-CN"),[ex,setEx]=useState(0),[vol,setVol]=useState(1000000),[streamTotal,setStreamTotal]=useState(0); const t=copy[lang], e=exchanges[ex], rebate=vol*e.f/100*e.r/100, monthlyFee=vol*.0004, annualRebate=rebate*12;
 useEffect(()=>{const update=()=>{const now=new Date(),dayStart=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),progress=Math.min(1,(now.getTime()-dayStart)/86400000);setStreamTotal(800*progress)};update();const timer=setInterval(update,10000);return()=>clearInterval(timer)},[]);
 const stream=useMemo(()=>{const seed=new Date().toISOString().slice(0,10).split("").reduce((a,c)=>a+c.charCodeAt(0),0),weights=exchanges.map((_,i)=>.65+((seed*(i+3)*17)%63)/100),sum=weights.reduce((a,b)=>a+b,0);return weights.map(x=>streamTotal*x/sum)},[streamTotal]);
 return <main className="siteShell"><div className="ambient" aria-hidden="true"><i/><i/><i/><i/></div><header><a className="brand" href="#"><i>₿</i><b>CRYPTO BONUS<span>CODE HUB</span></b></a><nav>{t.nav.map((x,i)=><a key={x} href={i===2?"/brief":"#"+(i===0?"rates":i===1?"calculator":"steps")}>{x}</a>)}</nav><select aria-label="Language" value={lang} onChange={x=>setLang(x.target.value as keyof typeof copy)}><option value="zh-CN">简体中文</option><option value="zh-TW">繁體中文</option><option value="en">English</option></select></header>
 <section className="hero"><div className="heroCopy"><p className="badge">● {t.badge}</p><h1>{t.title}</h1><p className="lead">{t.sub}</p><div className="actions"><a className="primary" href="#rates">{t.cta} →</a><a className="secondary" href="/brief">{t.brief}</a></div><div className="proof"><b>5</b> exchanges <b>0.04%</b> unified fee <b>Daily</b> reconciliation</div></div><div className="terminal"><div className="termTop"><span>REBATE STREAM · DEMO</span><em>● SIMULATED LIVE</em></div>{exchanges.map((x,i)=><div className="tick" key={x.n}><b>{x.n}</b><small>DAILY ALLOCATION</small><span>{x.r}% rebate</span><strong>+${stream[i].toFixed(2)}</strong></div>)}<div className="termFoot"><span>TODAY RETURNED <small>模拟数据 · 每日目标约 $800</small></span><b>${streamTotal.toFixed(2)}</b></div></div></section>
 <section id="rates" className="section"><p className="eyebrow">PARTNER NETWORK</p><h2>更低净费率，从清晰的数字开始</h2><div className="cards">{exchanges.map(x=><article key={x.n}><div className="exchange"><i>{x.n[0]}</i><b>{x.n}</b><span>DERIVATIVES</span></div><p>渠道返佣</p><h3>{x.r}%</h3><div className="metric"><span>统一手续费率</span><b>0.040%</b></div><div className="metric"><span>返佣后净费率</span><b>≈ {(x.f*(1-x.r/100)).toFixed(3)}%</b></div><div className="invite"><span>邀请码</span><strong>{x.code}</strong></div><button>复制邀请码 · 开户 →</button></article>)}</div><p className="disclaimer">测算统一按万四（0.04%）手续费计算。费率与资格因地区、账户状态及交易所政策而异，最终以交易所官方页面和账户显示为准。</p></section>
 <section id="calculator" className="calcWrap"><div className="calcIntro"><p className="eyebrow">30 秒测算</p><h2>你每月能返多少？拖一下就知道</h2></div><p className="calcLead">选择交易所、拖动月交易量，实时计算手续费与返佣后净费率。统一按万四手续费测算。</p><div className="calculator"><div className="calcBar"><span><i/>返佣测算台</span><b>LIVE ESTIMATE</b></div><div className="calcControls"><label>选择交易所<div className="exchangePills">{exchanges.map((x,i)=><button type="button" className={ex===i?"active":""} onClick={()=>setEx(i)} key={x.n}>{x.n}</button>)}</div></label><label>{t.volume}<strong>${vol.toLocaleString()}</strong><input type="range" min="100000" max="10000000" step="1000" value={vol} onChange={x=>setVol(+x.target.value)}/><div className="quickVolumes"><button onClick={()=>setVol(100000)}>$100K</button><button onClick={()=>setVol(1000000)}>$1M</button><button onClick={()=>setVol(10000000)}>$10M</button></div></label><div className="orderType"><span className="active">Taker 吃单&nbsp; 0.04%</span><span>Maker 挂单&nbsp; 0.04%</span></div></div><div className="calcOutput"><span>{t.result}</span><b>${rebate.toLocaleString(undefined,{maximumFractionDigits:2})}</b><small>≈ ${annualRebate.toLocaleString(undefined,{maximumFractionDigits:2})} / 年</small><div className="feeRow"><span>月手续费</span><strong>${monthlyFee.toLocaleString(undefined,{maximumFractionDigits:2})}</strong></div><div className="feeTrack"><i style={{width:`${e.r}%`}}/></div><p>● 返还 {e.r}% · ${rebate.toLocaleString(undefined,{maximumFractionDigits:2})}<em>净付 ${(monthlyFee-rebate).toLocaleString(undefined,{maximumFractionDigits:2})}</em></p><div className="rateCompare"><span>原始费率<del>0.040%</del></span><span>返佣后净费率<b>{(e.f*(1-e.r/100)).toFixed(3)}%</b></span></div></div></div></section>
 <section className="briefBand"><div><p className="eyebrow">DAILY INTELLIGENCE · 11 JUL 2026</p><h2>市场噪音很多，重点只有几个。</h2><p>每日追踪 BTC、ETH、资金流、宏观事件与关键风险位，用 3 分钟完成盘前准备。</p></div><a href="/brief">阅读今日简报 →</a></section>
 <section id="steps" className="section"><p className="eyebrow">HOW IT WORKS</p><h2>{t.steps}</h2><div className="steps">{[["01","选择交易所","比较返佣比例、费率与开户条件。"],["02","通过专属链接注册","确认邀请码已正确绑定，全程无需 API Key。"],["03","交易并获得返还","系统定期对账，符合条件的返佣按规则发放。"]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <footer><a className="brand" href="#"><i>₿</i><b>CRYPTO BONUS<span>CODE HUB</span></b></a><p>信息仅供参考，不构成投资建议。数字资产交易具有高风险。</p><span>© 2026 CryptoBonusCodeHub.com</span></footer></main>
}
