export type BriefItem={date:string;title:string;summary:string;points:[string,string,string];risk:string;sections?:{heading:string;paragraphs:string[]}[];marketTable?:{symbol:string;price:string;change:string;volume:string}[];sources?:{label:string;url:string}[]};
export const briefs:BriefItem[]=[
 {date:"2026-07-15",title:"强力修复，但风险尚未解除",summary:"低于预期的美国通胀为风险资产提供缓冲，台股与存储链剧烈反弹；但油价仍处高位，半导体仓位极度拥挤，ASML 与台积电业绩将决定修复能否转为盈利上修。",points:["台湾加权指数反弹约 2.2%，台积电回到 2450 新台币附近","SKHX、SKHY、DRAM、MU 与 SNDK 反弹约 8%–24%，空头回补力量强","6 月核心 CPI 明显降温，但 7 月能源冲击尚未计入，未来 24 小时进入业绩验证窗口"],risk:"强反弹同时包含基本面买盘、空头回补与杠杆清算；存储和全球半导体仍是最拥挤交易之一，必须等待正股成交、ETF 资金流、ASML 订单与台积电指引确认。",sections:[
  {heading:"核心结论",paragraphs:["市场正在进行强力技术修复，但还不能确认风险完全解除。台湾加权指数从昨日大跌中反弹约 2.2%，台积电回到 2450 新台币附近；TraderXYZ 存储链出现 8%–24% 的剧烈反弹。修复幅度说明空头回补和抄底资金很强，也反映波动率仍处高位。","美国 6 月 CPI 环比下降 0.4%，核心 CPI 环比持平、同比 2.6%，均明显降温。这降低了美联储立即转鹰的压力，是风险资产反弹的重要基础。","最新油价冲击尚未进入 6 月 CPI。WTI 和布伦特仍分别约 79.2、84.2 美元。7 月美伊冲突和霍尔木兹海峡风险可能重新推高汽油、运输与生产成本，不能用 6 月低通胀直接外推未来数月。","存储链基本面强，但已成为全球最拥挤交易之一。未来 24 小时的 ASML 二季度结果与 7 月 16 日台积电法说，将决定反弹能否从交易修复转为盈利预期上修。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 45722.81，较前收 44737.95 上涨约 2.20%；盘中区间 44850.69–45801.84。台积电开盘 2425，盘中区间 2415–2460，前收 2420；12:04 盘口约 2450–2455，较前收上涨约 1.2%–1.4%。","指数涨幅大于台积电，说明反弹扩散到其他电子、金融和传统板块，不再完全依赖单一权重股。市场报道台积电二季度营收约 1.27 万亿新台币，同比增长约 36%，上半年营收约 2.4 万亿新台币。","台积电当前更接近“强基本面等待估值确认”。若法说继续上调盈利和产能利用率预期，股价有望维持相对强势；若收入增长强但毛利率、资本开支回报或海外成本不理想，仍可能出现利好兑现。"]},
  {heading:"全球宏观与政策",paragraphs:["美国劳工统计局数据显示，6 月总体 CPI 环比 -0.4%，核心 CPI 环比 0.0%、同比 +2.6%。汽油价格下降是总体通胀回落的重要原因。","这份数据对应 6 月，而当前油价跳升发生在 7 月。政策判断需要同时看已实现的通胀下降与未来能源成本重新上升。WTI 约 79.23、布伦特约 84.17，24 小时涨幅虽收窄，但绝对价格仍高。","若油价停止继续上涨，低核心 CPI 将支持科技股估值修复；若布伦特进一步突破并稳定在更高区域，市场会重新交易通胀、加息和增长放缓风险。"]},
  {heading:"AI 与半导体产业链",paragraphs:["晶圆代工：台积电相对稳健，二季度营收保持高速增长。核心问题转向毛利率、先进封装产能和海外扩张成本。","设备：ASML 将于今天公布二季度结果，重点关注净订单、EUV/High-NA EUV 交付、2026 年收入及 2027 年需求展望。","GPU/加速器：NVDA 合约上涨约 4.38%，AMD 上涨约 3.94%。GPU 链反弹稳健，但弱于最拥挤的存储链，说明资金首先回补前一日跌幅最大的品种。","存储：SKHX +21.33%、SKHY +24.41%、DRAM +11.65%、MU +8.27%、SNDK +8.34%、SMSN +9.55%。SK 海力士管理层预计存储紧张可能延续至 2030 年，并把 2027 年视为供应最紧张阶段之一。"]},
  {heading:"机构观点与逆共识",paragraphs:["UBS 预计 AI 资本开支约为 2026 年 8200 亿美元、2027 年 9900 亿美元，实际数字仍可能更高；半导体估值并非典型泡沫，但资本开支增速放缓会压缩硬件估值。","美国银行基金经理调查显示，“做多全球半导体”仍是最拥挤交易之一。Man Group 的 Sumant Wahi 认为 AI 交易已从广泛主题行情转向更战术化的个股选择。","Coronation 刻意保持较低半导体仓位，主要通过台积电参与，并用保护性看跌期权控制风险。Franklin Templeton/ClearBridge 认为 AI 广度可能延长传统半导体周期，但最终只有具备持续竞争优势的龙头胜出。","逆共识风险是供需强劲已经被拥挤仓位和高估值充分定价。今天 20% 以上的反弹不只代表基本面，也可能是空头回补；越强的短线涨幅，越需要现货成交、盈利上修和订单验证。"]},
  {heading:"今日观察框架",paragraphs:["关注台湾加权指数能否稳定在 45500 上方、台积电能否维持 2450 附近，并观察反弹是否继续扩散。","ASML 结果重点看净订单而非单季收入；净订单更能反映台积电、三星、Intel 等客户未来产能计划。","美股开盘后比较 SKHY、MU、SNDK 与 NVDA、AMD 的相对强弱；若存储链冲高回落而 GPU 链稳定，说明拥挤交易仍在消化。","继续监控美债收益率和布伦特油价。台积电法说后，以盈利预期是否上修作为判断标准，不以单日股价涨跌替代基本面结论。"]}
 ],marketTable:[{symbol:"SKHX",price:"1449.3",change:"+21.33%",volume:"14.445 亿美元"},{symbol:"SKHY",price:"191.46",change:"+24.41%",volume:"4.109 亿美元"},{symbol:"CL",price:"79.225",change:"+0.10%",volume:"3.714 亿美元"},{symbol:"XYZ100",price:"29818",change:"+1.99%",volume:"3.522 亿美元"},{symbol:"DRAM",price:"62.776",change:"+11.65%",volume:"2.902 亿美元"},{symbol:"MU",price:"1002.0",change:"+8.27%",volume:"2.565 亿美元"},{symbol:"BRENTOIL",price:"84.17",change:"+0.49%",volume:"2.551 亿美元"},{symbol:"SP500",price:"7561.3",change:"+0.85%",volume:"2.500 亿美元"},{symbol:"SNDK",price:"1794.9",change:"+8.34%",volume:"2.084 亿美元"},{symbol:"SPCX",price:"138.08",change:"+0.44%",volume:"1.372 亿美元"}],sources:[{label:"美国劳工统计局：2026 年 6 月 CPI",url:"https://www.bls.gov/news.release/cpi.htm?lv=true"},{label:"台积电 2026 年第二季度业绩页面",url:"https://investor.tsmc.com/english/quarterly-results/2026/q2"},{label:"台积电 2026 年月度营收",url:"https://investor.tsmc.com/english/monthly-revenue/2026"},{label:"ASML 2026 年第二季度业绩页面",url:"https://www.asml.com/en/investors/financial-results/q2-2026"},{label:"台湾证券交易所即时行情",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"Hyperliquid API 文档",url:"https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint/perpetuals"},{label:"AP：油价跳涨与 AI 股票下跌",url:"https://apnews.com/article/2d6744b09c68b5473d0bc8584b89e60e"},{label:"UBS：AI 资本开支与半导体选择",url:"https://www.ubs.com/us/en/wealth-management/insights/market-news/article.3534348.html"},{label:"Man Group：半导体交易进入选择阶段",url:"https://www.man.com/insights/views-from-the-floor-2026-14-july"},{label:"Coronation 基金 2026 年 7 月观点",url:"https://www.coronation.com/en-us/institutional/articles/2026/july/Coronation-optimum-growth-usd-fund-july-2026/"},{label:"Franklin Templeton：AI 资本开支能否延长半导体周期",url:"https://www.franklintempleton.com/articles/2026/clearbridge-investments/can-ai-capex-extend-the-semiconductor-cycle"},{label:"台积电上半年营收报道",url:"https://cincodias.elpais.com/companias/2026-07-13/tsmc-el-mayor-productor-mundial-de-chips-registra-unos-ingresos-record-gracias-a-la-demanda-de-la-ia.html"}]},
 {date:"2026-07-14",title:"能源冲击接管市场定价",summary:"美伊冲突与霍尔木兹海峡风险推动油价急升，台股出现系统性去风险，存储链继续成为回撤中心；AI 资本开支仍强，但市场已进入验证现金回报的阶段。",points:["WTI 与布伦特合约分别上涨约 6.85% 和 6.24%，能源冲击压缩科技股估值","台湾加权指数盘中跌约 2.8%，跌幅大于台积电，显示系统性风险释放","SKHX、SNDK、DRAM 与 MRVL 明显承压，7 月 16 日台积电法说成为关键验证点"],risk:"油价、通胀预期和美债收益率正在同步抬升；TraderXYZ 可用于观察风险方向，但仍须以美股正股、ETF 资金流和期权波动率确认精确定价。",sections:[
  {heading:"核心结论",paragraphs:["今天的首要变量已从 AI 需求切换为能源冲击。美伊冲突重新升级、霍尔木兹海峡运输风险上升，周一布伦特一度上涨约 9.6%；截至中午，TraderXYZ 的 WTI 与布伦特仍分别上涨约 6.85% 和 6.24%。油价、通胀预期与美债收益率同步上行，直接压缩高估值科技股的估值空间。","台股出现系统性风险释放，不只是台积电个股问题。台湾加权指数盘中最低约 43654，12:13 约 44115，较前收 45381 下跌约 2.8%；台积电盘中 2390–2430，前收 2440。指数跌幅显著大于台积电，说明其他电子、金融和传统产业也在同步去风险。","存储链仍是本轮回撤中心。SK 海力士相关合约、闪迪、DRAM 与 MRVL 跌幅明显，成交量显著放大。中期供需逻辑尚未被单日行情否定，但短期拥挤度、获利盘与宏观折现率正在共同施压。","AI 资本开支尚未见顶，但股票市场已进入“验证回报”阶段。需求、订单和资本开支可以继续增长，股价却可能因估值过高、资金连续减仓和油价冲击而调整。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 44114.79，较前收 45380.52 下跌约 2.79%；盘中区间 43654.04–45364.40。台积电开盘 2410，盘中区间 2390–2430，前收 2440；按盘口附近 2405–2410 估算，跌幅约 1.2%–1.4%。","台积电占台湾市场权重极高，但今天指数跌幅大于台积电，说明并非单一权重股拖累，而是广泛风险偏好下降。公司将于 7 月 16 日 14:00（台湾时间）举行二季度业绩说明会。","台积电相对大盘仍有一定韧性，但不能把“跌得少”直接等同于调整结束。若油价继续维持高位、利率预期转鹰，即使法说基本面强，估值扩张也会受限。重点应是法说后盈利预期能否继续上修。"]},
  {heading:"全球宏观与政策风险",paragraphs:["Reuters 报道，美伊在周末恢复大规模导弹和无人机交火，伊朗称再次关闭霍尔木兹海峡；美国随后宣布恢复对伊朗港口的海上封锁。AP 报道，周一布伦特上涨约 9.6%至 83.30 美元附近，芯片及 AI 概念股同步下跌，美债收益率随油价走高。","当前担忧的传导路径是：海峡运输受阻 → 原油与 LNG 价格上行 → 通胀重新抬头 → 美联储更难降息 → 长久期科技股估值下压。","本周美国 CPI、PPI 数据将检验能源冲击向物价的传导程度。若通胀高于预期且油价不回落，科技股的宏观压力会进一步增加。"]},
  {heading:"半导体、AI 与上下游",paragraphs:["晶圆代工：台积电盘中跌幅小于大盘，说明资金仍认可先进制程与 AI 代工的相对确定性；7 月 16 日法说将决定这种相对强势能否持续。","GPU/加速器：NVDA 合约约跌 1.98%，AMD 约跌 1.36%，弱于大盘合约但好于部分存储和网络芯片。AI 核心算力需求尚未出现直接反转证据。","存储：SKHX 跌 7.64%、DRAM 跌 3.04%、SKHY 跌 3.64%、SNDK 跌 9.22%；MU 跌幅收窄至约 0.28%–0.63%。资金更集中卖出此前涨幅更大、筹码更拥挤的品种。","网络/定制芯片：MRVL 跌约 6.02%，说明市场在削减数据中心扩建链条中弹性更高、估值更敏感的环节。原油跳涨也提高数据中心电力、运输、化工和设备制造成本。"]},
  {heading:"机构观点与逆共识",paragraphs:["BMO Capital Markets 的 Ian Lyngen 认为，当前全球市场价格主要由霍尔木兹海峡状态驱动，能源板块重新成为市场核心。GLOBALT 的 Thomas Martin 指出，芯片股此前已推动市场达到高位，而当前市场并不便宜，宏观冲击下估值缺少缓冲垫。","摩根士丹利的中期框架仍认为 AI 投资支持美国增长，但能源是最大不确定因素。摩根资管认为 AI 资本开支仍直接利好供应链，不过云厂商资本开支占经营现金流比例已明显上升，未来必须更快证明投资回报。","逆共识风险是：资本开支上行本身可能推高融资需求、能源需求和利率，使供应链盈利增长无法完全转化为股价上涨。今天油价与芯片股的负相关正在验证这一风险。"]},
  {heading:"今日观察与执行框架",paragraphs:["先观察油价能否回落至周一跳涨前区域。油价不回落时，不应仅凭科技股跌幅较大就判断宏观压力已经出清。","台股关注 44000 点附近承接、台积电 2390–2400 区间以及外资净流向；若指数修复但成交缩量，反弹质量有限。","美股开盘后比较存储链与 GPU 链的相对强弱。若 MU、SKHY、SNDK 继续显著弱于 NVDA、AMD，说明市场主要在处理存储拥挤度，而非否定整个 AI 需求。","7 月 16 日台积电法说重点跟踪全年营收增速、资本开支、先进封装产能、2nm/3nm 进展、毛利率及海外厂成本。"]}
 ],marketTable:[{symbol:"SKHX",price:"1178.3",change:"-7.64%",volume:"15.429 亿美元"},{symbol:"CL",price:"79.294",change:"+6.85%",volume:"4.557 亿美元"},{symbol:"XYZ100",price:"29182",change:"-0.97%",volume:"3.761 亿美元"},{symbol:"DRAM",price:"55.602",change:"-3.04%",volume:"2.964 亿美元"},{symbol:"MU",price:"921.37",change:"-0.63%",volume:"2.609 亿美元"},{symbol:"BRENTOIL",price:"83.886",change:"+6.24%",volume:"2.176 亿美元"},{symbol:"SP500",price:"7491.8",change:"-0.53%",volume:"2.151 亿美元"},{symbol:"SKHY",price:"152.93",change:"-3.64%",volume:"2.072 亿美元"},{symbol:"SNDK",price:"1648.1",change:"-9.22%",volume:"2.059 亿美元"},{symbol:"SILVER",price:"57.598",change:"-0.88%",volume:"1.720 亿美元"}],sources:[{label:"台积电 2026 年第二季度业绩页面",url:"https://investor.tsmc.com/english/quarterly-results/2026/q2"},{label:"台积电 2026 年月度营收",url:"https://investor.tsmc.com/english/monthly-revenue/2026"},{label:"台湾证券交易所即时行情",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"Hyperliquid API 文档",url:"https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint/perpetuals"},{label:"Reuters：海湾冲突升级、油价及债券收益率上升",url:"https://au.investing.com/news/commodities-news/shares-slip-in-asia-as-oil-jumps-on-gulf-attacks-4528787"},{label:"Reuters：美股因伊朗局势与芯片股下跌而走弱",url:"https://au.marketscreener.com/news/wall-street-slips-as-iran-tensions-hit-sentiment-chipmakers-drop-ce7f5edcdb88f327"},{label:"AP：油价跳涨、AI 股票下跌",url:"https://apnews.com/article/2d6744b09c68b5473d0bc8584b89e60e"},{label:"Bloomberg：油价续涨、亚洲股市承压",url:"https://www.swissinfo.ch/eng/oil-extends-advance%2C-asian-stocks-set-to-decline%3A-markets-wrap/91740941"},{label:"摩根士丹利 2026 年中展望",url:"https://www.morganstanley.com/Themes/outlooks"},{label:"摩根资管：AI 需求与资本开支",url:"https://am.jpmorgan.com/se/en/asset-management/adv/insights/market-insights/investment-outlook/technology-and-ai/"},{label:"Amundi 2026 年 7 月全球投资观点",url:"https://research-center.amundi.com/article/global-investment-views-july-2026"}]},
 {date:"2026-07-13",title:"台股现货强势，存储链周末降温",summary:"台积电与台湾加权指数维持强势，周末存储链明显回吐、原油走高；AI 资本开支仍在上修，但利率、油价与拥挤筹码正压低估值容错率。",points:["台积电盘中约 2445–2475 新台币，先进制程仍是台股核心支撑","SKHX、DRAM、三星与闪迪相关合约回落约 5%–11%，更像拥挤交易降温","AI 资本开支尚未见顶，但油价、利率和连续减仓成为短线关键变量"],risk:"周末 TraderXYZ 成交集中且规模有限，只适合观察边际情绪；周一仍需用正股成交量、SOXX/SMH 资金流和期权波动率二次确认。",sections:[
  {heading:"核心结论",paragraphs:["台股现货强于周末存储链情绪。台积电盘中区间约 2445–2475 新台币，前收 2415；台湾加权指数约 45696，盘中最高约 46331。先进制程与 AI 代工龙头仍是台湾市场的主要支撑。","周末风险结构是“存储回吐、原油走强”。SK 海力士、DRAM、三星、闪迪相关合约普遍下跌约 5%–11%，而 WTI/布伦特约涨 1.2%。这更像拥挤交易降温与地缘风险溢价回归，不足以单独证明存储基本面反转。","AI 资本开支尚未见顶，但市场开始要求现金回报。机构继续上调云厂商资本开支估计，供应链收入景气仍强，但估值容错率下降。","短线最重要变量不是需求，而是油价、利率和筹码。原油与美债收益率上行会抬高折现率；对冲基金已连续第四周净卖出科技硬件/半导体。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 45696.59，较前收高约 0.75%；盘中区间 45500.32–46330.91。台积电开盘 2460，盘中区间 2445–2475，前收 2415。由于抓取时最新成交价字段短暂为空，以上以盘口与日内区间为准。","台积电官网在数据截点仍未显示 6 月营收。1–5 月累计营收约 1.962 万亿新台币，同比增长 30.0%。今天的上涨更多是市场对 AI/先进制程景气的定价，尚不是新增月营收数据确认。","中期逻辑仍由先进制程、CoWoS/先进封装与 AI 加速器需求共同支撑；下一步观察月营收、二季度法说、先进封装扩产和主要客户下半年交付指引。"]},
  {heading:"全球宏观与美股主线",paragraphs:["上周美股在芯片股带动下修复，但周末 SP500 合约约跌 0.33%，XYZ100 约跌 0.93%，显示风险偏好略降。WTI 约涨 1.25%，布伦特约涨 1.19%。若油价延续上行，市场会重新评估通胀与降息路径。","摩根士丹利的中期基准情景仍偏建设性，认为 AI 投资支撑增长，同时将能源冲击列为最大宏观变量。Amundi 更谨慎，认为央行转鹰、AI 估值和集中度以及存储股涨幅过快正在压缩容错空间。"]},
  {heading:"半导体、AI 与上下游",paragraphs:["上游设备/晶圆代工：台积电现货走强，先进制程主线仍获资金认可；能源、设备交付及先进封装产能仍是瓶颈。","GPU/加速器：NVDA 约跌 0.21%，明显好于存储链，说明周末抛压集中在此前涨幅更大、交易更拥挤的内存板块。","存储：MU 约跌 3.71%、DRAM 约跌 6.55%、SKHX 约跌 10.56%、SNDK 约跌 5.68%、SMSN 约跌 6.07%。短线是降温信号，中期仍需用 HBM 合同价格、库存、产能利用率与资本开支验证。","网络/定制芯片：MRVL 约跌 2.49%。若云厂商继续上调资本开支，网络互连、光模块、定制 ASIC 与先进封装仍是第二梯队受益方向。"]},
  {heading:"机构观点与逆共识",paragraphs:["摩根士丹利认为 AI 基建资本开支周期仍在加速，同时警告融资需求将增加公司债供给。摩根资管估计五家美国超大规模公司 2026 年资本开支约 6970 亿美元。","高盛主经纪数据显示，对冲基金连续第四周净卖出科技硬件和半导体，并转向指数/ETF、能源与防御板块。Amundi 则主张把风险分散至欧洲、日本、工业、材料和电力基础设施。","即使终端需求没有见顶，芯片股也可能先因利率、估值与拥挤交易而调整。产业景气与股票回报需要分开判断。"]},
  {heading:"今日观察与策略框架",paragraphs:["观察台积电能否在放量情况下维持 2445–2475 区间上方强势，而不只是早盘跳空。","美股开盘重点比较 MU、SK Hynix ADR、SNDK 与 NVDA、AMD 的相对强弱；若存储跌幅快速收窄，周末价格更可能只是低流动性扰动。","同步监控 WTI、10 年期美债收益率和 SOXX/SMH。油价与收益率同步上行时，不宜仅凭产业利好追逐高估值。中期优先选择订单、产能和盈利上修可以验证的环节。"]}
 ],marketTable:[{symbol:"SKHX",price:"1312.2",change:"-10.56%",volume:"3.927 亿美元"},{symbol:"XYZ100",price:"29547",change:"-0.93%",volume:"1.372 亿美元"},{symbol:"CL",price:"74.369",change:"+1.25%",volume:"1.327 亿美元"},{symbol:"SP500",price:"7541.6",change:"-0.33%",volume:"0.891 亿美元"},{symbol:"BRENTOIL",price:"79.098",change:"+1.19%",volume:"0.876 亿美元"},{symbol:"MU",price:"940.88",change:"-3.71%",volume:"0.739 亿美元"},{symbol:"DRAM",price:"58.734",change:"-6.55%",volume:"0.728 亿美元"},{symbol:"SILVER",price:"58.556",change:"-1.99%",volume:"0.541 亿美元"},{symbol:"SKHY",price:"160.92",change:"-6.39%",volume:"0.532 亿美元"},{symbol:"SNDK",price:"1836.8",change:"-5.68%",volume:"0.417 亿美元"}],sources:[{label:"台积电 2026 年月度营收",url:"https://investor.tsmc.com/english/monthly-revenue/2026"},{label:"台积电财务日历",url:"https://investor.tsmc.com/english/financial-calendar"},{label:"台湾证券交易所即时行情",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"摩根士丹利 2026 年中展望",url:"https://www.morganstanley.com/Themes/outlooks"},{label:"摩根资管：AI 需求与资本开支",url:"https://am.jpmorgan.com/se/en/asset-management/adv/insights/market-insights/investment-outlook/technology-and-ai/"},{label:"Amundi 2026 年 7 月全球投资观点",url:"https://research-center.amundi.com/article/global-investment-views-july-2026"},{label:"Reuters：对冲基金连续减持芯片股",url:"https://www.investing.com/news/stock-market-news/hedge-funds-dumped-chip-stocks-for-a-fourth-week-as-ai-shares-sold-off-4776190"}]},
 {date:"2026-07-10",title:"AI 硬件从防守转向修复",summary:"存储与内存链在高成交中反弹，油价降温缓解科技估值压力。",points:["SKHX、MU、SNDK 与 DRAM 出现高成交修复","AI 资金重新集中到订单与产能可见的瓶颈环节","原油回落，为科技股估值提供喘息空间"],risk:"单日反弹不代表趋势重置，仍需营收、指引与持续成交确认。"},
 {date:"2026-07-09",title:"AI 半导体收窄到龙头",summary:"NVDA 保持强势，TSMC 在关键位下方整理，内存交易继续去拥挤。",points:["NVDA 相对强势，资金更偏向确定性龙头","TSMC 在突破位下方消化筹码","内存链波动加大，拥挤度开始下降"],risk:"龙头强势不等于板块全面扩散，注意高估值资产的回撤风险。"},
 {date:"2026-07-08",title:"AI 半导体进入验证交易",summary:"存储资产选择性修复，市场尚未形成全面风险偏好。",points:["市场从预期交易转向数据和业绩验证","存储链出现选择性反弹而非全面上行","资金继续观察现金市场与永续合约是否共振"],risk:"缺少成交量配合的反弹持续性有限。"},
 {date:"2026-07-07",title:"TSMC 测试关键位，存储永续去风险",summary:"现金市场乐观情绪与存储相关永续合约卖压形成分歧。",points:["TSMC 再次靠近重要突破位置","现金股表现与永续合约资金流出现背离","MU、SKHX 与 DRAM 相关仓位主动降杠杆"],risk:"跨市场背离扩大时，应降低杠杆并等待方向确认。"},
 {date:"2026-07-06",title:"TSM 再次测试突破，MU 防守关键区间",summary:"AI 硬件仍处于防守验证阶段，HYPE 引领加密市场 Beta。",points:["TSM 重新测试前期压力区","MU 在关键区间寻找买盘支撑","HYPE 相对强势，带动加密市场风险偏好"],risk:"硬件链与加密 Beta 尚未完全同步，避免追逐短期波动。"},
 {date:"2026-07-03",title:"硬件链继续洗盘，加密 Beta 回升",summary:"内存和存储链承压，META 商业化预期与 HYPE 推动资金轮动。",points:["内存与存储链在高成交中继续去杠杆","META 的算力商业化叙事吸引资金","HYPE 推动加密市场风险偏好回升"],risk:"资金轮动速度快，强势资产也可能出现剧烈回吐。"},
 {date:"2026-07-02",title:"AI 交易从硬件建设转向算力变现",summary:"META 的算力云计划走强，硬件供应链进入压力测试。",points:["资金从资本开支叙事转向收入兑现","META 算力云计划强化商业化预期","TSM、MU 与设备股面临估值压力测试"],risk:"商业化预期需要订单和利润率验证。"},
 {date:"2026-07-01",title:"半导体获得第二次确认",summary:"TSM、AMD 与设备股确认资本开支广度，MU 消化涨幅。",points:["TSM 与 AMD 延续强势确认","设备股同步走强，资本开支广度改善","MU 高位整理，等待下一轮催化"],risk:"板块确认后仍要观察成交是否持续，防止假突破。"},
 {date:"2026-06-29",title:"AI 内存趋势仍在，MU 等待二次确认",summary:"MU 保持高流量，台湾市场 TSM 反弹，宏观数据限制估值扩张。",points:["MU 仍是内存链主要资金焦点","台湾现金市场推动 TSM 修复","通胀数据限制科技股估值扩张"],risk:"宏观利率重新上行可能压制高估值半导体。"},
 {date:"2026-06-01",title:"AI 硬件维持强势",summary:"台湾现金市场确认 TSM，HYPE 支撑风险偏好。",points:["台湾现金市场确认 TSM 买盘","AI 硬件主线保持相对强势","HYPE 为加密风险偏好提供支撑"],risk:"高位趋势中应关注量价背离与拥挤度。"},
 {date:"2026-05-30",title:"半导体高位轮动",summary:"MU 受益于 HBM 主题，TSM 与 NVDA 降温，HYPE 维持强势。",points:["MU 继续受益于 HBM 需求叙事","TSM 与 NVDA 高位降温","HYPE 在加密资产中保持相对强势"],risk:"高位轮动不等于风险消失，注意龙头补跌。"},
 {date:"2026-05-29",title:"AI 半导体进入高位分化",summary:"TSM 与 NVDA 上涨，MU 高位换手。",points:["TSM 延续现金市场强势","NVDA 保持 AI 核心资产地位","MU 高位成交放大、筹码换手"],risk:"分化阶段追高胜率下降，应等待明确支撑位。"},
 {date:"2026-05-28",title:"资金转向确定性",summary:"TSM 与 MU 领涨，NVDA 短线降温。",points:["资金偏好订单更清晰的供应链资产","TSM 与 MU 成为当日主要强势标的","NVDA 短线降温但核心叙事未变"],risk:"确定性交易拥挤后，同样可能出现快速估值收缩。"}
];
export const getBrief=(date:string)=>briefs.find(x=>x.date===date);
