export type BriefItem={date:string;title:string;summary:string;points:[string,string,string];risk:string;sections?:{heading:string;paragraphs:string[]}[];marketTable?:{symbol:string;price:string;change:string;volume:string}[];sources?:{label:string;url:string}[]};
export const briefs:BriefItem[]=[
 {date:"2026-07-20",title:"技术企稳，但能源与估值压力仍在",summary:"台股与台积电在上周急跌后出现技术性修复，周末 TraderXYZ 情绪温和回升；AI 基本面仍强，但高估值、拥挤仓位与持续上升的能源成本使趋势反转尚未得到确认。",points:["台湾加权指数接近平盘，台积电反弹约 1.7%–2.0%，首先应视作超跌修复","周末前十名义成交量约 13.5 亿美元，较上周五下降约 63%，信号可信度偏低","WTI 与布伦特约 83.8、88.2 美元，本周转向云厂商资本开支与全球政策验证"],risk:"恐慌暂时缓和不等于芯片股已经见底。高油价、海外扩产成本、自由现金流压力和高度拥挤的半导体仓位仍可能放大波动。",sections:[
  {heading:"核心结论",paragraphs:["台股出现技术性企稳，但尚未确认趋势反转。台湾加权指数接近平盘，台积电较前收反弹约 1.7%–2.0%。上周五台股成交额约 1.213 万亿新台币、台积电收跌 7.29%，今天的回升首先应视为超跌修复。","AI 产业基本面仍强，股票层面仍在消化高估值和拥挤仓位。台积电利润增长 77%、全年收入指引上调，ASML 也提高收入和设备产能计划，但全球芯片股仍连续下跌。市场已从需求是否存在转向资本开支能否产生足够回报。","周末 TraderXYZ 信号偏温和修复，但前十名义成交量仅约 13.5 亿美元，较上周五约 36.4 亿美元大幅下降，不足以确定美股正股开盘价格。","能源风险进一步上升。WTI 约 83.8 美元、布伦特约 88.2 美元。亚洲能源进口经济体和高耗电 AI 基础设施同时面临成本上升。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 42707.92，较前收 42671.27 上涨约 0.09%；盘中区间 41967.75–43084.51。台积电盘口约 2330–2335 新台币，前收 2290，涨幅约 1.7%–2.0%；盘中区间 2300–2345。","指数从日内低点回升约 740 点，但仍低于盘中高点，显示抄底与减仓力量并存。上周五台积电收于 2290、下跌 7.29%，台湾主板成交额约 1.213 万亿新台币，说明此前下跌伴随真实的大规模换手。","台积电收入和订单趋势仍健康，当前调整主要来自利润率、自由现金流、海外扩产成本与仓位拥挤。在毛利率预期稳定、外资流向改善和半导体 ETF 止跌前，不宜把单日反弹视为调整结束。"]},
  {heading:"台积电财报后的重新定价",paragraphs:["二季度美元收入 402 亿美元，毛利率 67.7%，净利润 7066 亿新台币，同比增长约 77%。2026 年美元收入增速上调至略高于 40%，资本开支上调至 600 亿–640 亿美元。","三季度收入指引 446 亿–458 亿美元，毛利率指引 65%–67%。新增 1000 亿美元美国投资后，总体美国投资承诺约 2650 亿美元。","中期基本面不应因数日股价下跌而被否定，但市场正更严格审查毛利率、海外成本和资本开支回报。"]},
  {heading:"上周全球市场复盘",paragraphs:["上周五标普 500 下跌约 1.0%，道指下跌约 0.8%，纳指下跌约 1.4%；Nvidia 下跌约 2.2%，芯片及 AI 高估值品种仍是主要拖累。","台北指数上周五下跌约 6.5%，日本约跌 4%，上海约跌 3%，去风险已扩散到主要亚洲市场。","标普 500 结束近三周以来首个下跌周，但距离此前历史高位仍不远，整体市场尚未进入全面熊市定价，更接近高估值板块集中调整。"]},
  {heading:"全球宏观与政策",paragraphs:["美国本周关注 S&P Global 制造业与服务业 PMI，以及 7 月 28–29 日美联储会议前的利率定价。欧洲市场预计 ECB 维持存款利率 2.25% 不变，但将关注能源冲击下的通胀措辞。","中国市场预计一年期和五年期 LPR 分别维持 3.0% 和 3.5% 不变。日本与英国通胀数据将检验能源冲击传导，日元低位增加日本输入型通胀风险。","WTI 约 83.77、布伦特约 88.22。美国与伊朗冲突及关键航道风险仍是全球通胀最大不确定因素之一。"]},
  {heading:"AI 与半导体产业链",paragraphs:["晶圆代工：台积电基本面最强，但市场开始把资本开支和海外成本纳入估值。设备：ASML 产能计划与台积电资本开支上调提高订单可见度。","GPU：NVDA 合约约涨 0.59%、AMD 约涨 2.21%，但成交量低，需等待美股开盘验证机构资金是否真正回流。","存储：SKHX +1.46%、SKHY +1.26%、MU +1.99%、DRAM +0.06%、SNDK 基本持平，三星相关合约反而跌 2.55%，内部尚未形成一致方向。","本周云厂商资本开支比单纯芯片价格更关键。Alphabet 的 AI 投资、云收入和模型商业化将影响网络、ASIC、光通信、先进封装和电力基础设施。"]},
  {heading:"机构观点与逆共识",paragraphs:["BofA 7 月全球基金经理调查显示，82% 的受访基金经理把做多全球半导体列为最拥挤交易；AI 超大规模云厂商资本开支也被视为潜在系统性信用事件来源。","UBS 认为 AI 需求逻辑仍完整，但波动要求投资者分散配置、主动选股，并把机会扩展到软件、数据中心与能源基础设施。","Allianz Taiwan 的 Corrina Xiao 认为台积电强财报后仍大跌，主要因投资者聚焦三季度毛利率弱于预期。ACCM 的 Glenn Yin 指出，资本开支增加和海外扩张成本成为市场重点。","逆共识是：资本开支可能通过债务融资、折旧、能源消耗和潜在过剩降低股东回报。芯片公司即使继续超预期，也可能在一段时间内跑输盈利增长。"]},
  {heading:"本周观察与策略框架",paragraphs:["台湾市场观察 42000–43000 点区间承接，以及台积电能否稳定在 2300 上方并出现缩量止跌。","美国科技重点跟踪 Alphabet 资本开支、云收入和 AI 商业化；Tesla 关注汽车毛利率、自动驾驶和储能。","若 SOXX/SMH 止跌而盈利预期继续上修，可判断估值压缩接近尾声；若盈利预期同步下调，则调整性质恶化。","宏观重点关注布伦特 90 美元关口、ECB 措辞、欧美 PMI、美元与美债收益率。中期优先考虑有订单、产能和现金流验证的企业。"]}
 ],marketTable:[{symbol:"SKHX",price:"1193.8",change:"+1.46%",volume:"5.214 亿美元"},{symbol:"XYZ100",price:"28680",change:"+0.61%",volume:"1.324 亿美元"},{symbol:"SP500",price:"7460.7",change:"+0.35%",volume:"1.306 亿美元"},{symbol:"CL",price:"83.767",change:"+0.26%",volume:"1.135 亿美元"},{symbol:"BRENTOIL",price:"88.216",change:"-0.06%",volume:"0.813 亿美元"},{symbol:"SILVER",price:"56.963",change:"+1.69%",volume:"0.804 亿美元"},{symbol:"SNDK",price:"1358.6",change:"-0.01%",volume:"0.779 亿美元"},{symbol:"DRAM",price:"52.675",change:"+0.06%",volume:"0.747 亿美元"},{symbol:"MU",price:"862.19",change:"+1.99%",volume:"0.713 亿美元"},{symbol:"SKHY",price:"156.39",change:"+1.26%",volume:"0.659 亿美元"}],sources:[{label:"台积电 2026 年第二季度官方业绩",url:"https://investor.tsmc.com/english/quarterly-results/2026/q2"},{label:"台湾证券交易所即时行情",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"Taipei Times：7 月 17 日台股成交与下跌",url:"https://www.taipeitimes.com/News/front/archives/2026/07/18/2003860942"},{label:"AP：全球 AI 股票抛售与油价上涨",url:"https://apnews.com/article/65449e9565fba441a617f9517e097f5a"},{label:"Reuters：全球芯片股下跌",url:"https://www.investing.com/news/economy-news/asian-shares-slump-on-chipmaker-drag-bonds-cheer-cooler-inflation-4794608"},{label:"UBS：以分散和精选应对 AI 波动",url:"https://www.ubs.com/global/en/wealthmanagement/insights/chief-investment-office/house-view/daily/2026/latest-06072026.html"},{label:"本周全球央行与 PMI 前瞻",url:"https://au.marketscreener.com/news/week-ahead-for-fx-bonds-u-s-european-pmi-data-ecb-decision-in-focus-ce7f51dade8dff20"},{label:"DBS 本周宏观前瞻",url:"https://www.dbs.com.tw/personal/aics/templatedata/article/generic/data/en/GR/072026/260717_insights_week_ahead.xml"},{label:"IMF 2026 年 7 月世界经济展望更新",url:"https://www.imf.org/-/media/files/publications/weo/2026/update/july/english/text.pdf"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"Hyperliquid API 文档",url:"https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint/perpetuals"},{label:"Man Group：半导体交易进入选择阶段",url:"https://www.man.com/insights/views-from-the-floor-2026-14-july"}]},
 {date:"2026-07-17",title:"强财报之后，市场转向资本回报率",summary:"台积电交出创纪录业绩并大幅上调收入与资本开支，但市场进入“好消息不够好”阶段；AI 科技板块跨市场去风险，投资者开始从需求叙事转向毛利率、自由现金流与资本回报率。",points:["台积电二季度美元收入 402 亿、毛利率 67.7%、净利润同比增长约 77%","全年美元收入增速上调至略高于 40%，资本开支升至 600亿–640 亿美元","台湾加权指数与台积电均跌约 5%，GPU、存储和网络芯片同步去杠杆"],risk:"AI 需求没有见顶，但高预期、毛利率边际回落、资本开支激增、海外扩产成本和拥挤仓位正在共同压缩估值；高油价也使宏观压力难以完全消退。",sections:[
  {heading:"核心结论",paragraphs:["台积电交出极强财报，但市场进入“好消息不够好”阶段。二季度美元收入 402 亿美元、毛利率 67.7%、净利润 7066 亿新台币，同比增长约 77%；全年美元收入增速上调至略高于 40%。基本面没有显示 AI 需求见顶。","股价下跌的核心不是需求转弱，而是估值、资本开支和利润率再定价。台积电将 2026 年资本开支上调至 600 亿–640 亿美元，并新增 1000 亿美元美国投资；三季度毛利率指引 65%–67%，低于二季度 67.7%。","今天已从存储链内部波动升级为 AI 科技板块广泛去风险。台湾加权指数与台积电盘中均跌约 5%；TraderXYZ 的纳指、GPU、存储、网络芯片和韩国 ETF 同步下跌，跨市场信号一致。","ASML 与台积电共同证明资本开支仍在上行。产业链景气仍强，但扩产越快，市场越会担心 2027–2028 年供需、融资成本与资本回报率。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 43248.69，较前收 45624.98 下跌约 5.21%；盘中区间 43178.22–45234.08。台积电约 2345 新台币，较前收 2470 下跌约 5.06%；开盘 2375，盘中区间 2340–2395，成交量明显放大。","指数与台积电同步大跌，说明权重股、电子链及市场风险偏好共同承压，不是单一公司事件。","台积电中期基本面仍偏多，但股价下跌说明市场已不再争论需求是否强，而在争论高资本开支能否产生足够自由现金流。短期估值和仓位风险仍未释放完毕。"]},
  {heading:"台积电二季度关键数据",paragraphs:["美元收入 402 亿美元，达到此前指引上沿；新台币收入约 1.27 万亿，同比增长约 36%。毛利率 67.7%，营业利润率 60.3%；净利润 7066 亿新台币，同比增长约 77%，显著高于市场预期。","三季度收入指引 446 亿–458 亿美元，毛利率指引 65%–67%，营业利润率指引 56%–58%。2026 年美元收入增速上调至略高于 40%，资本开支上调至 600 亿–640 亿美元。","美国扩产新增 1000 亿美元承诺，预计增加四座先进晶圆厂，总体美国投资承诺提高至约 2650 亿美元。2nm 已贡献约 3% 晶圆收入，3nm 约 30%、5nm 约 33%、7nm 约 11%。","2nm 快速爬坡会带来折旧、良率和初期成本压力；美国、日本与欧洲扩张提高供应链韧性，但短中期成本结构通常弱于台湾本土产能。"]},
  {heading:"为什么强财报仍然下跌",paragraphs:["预期门槛过高：台积电、ASML 与存储龙头此前涨幅巨大，单纯超预期已不足以推动估值继续扩张。","毛利率边际回落：三季度 65%–67% 指引低于二季度 67.7%，2nm 爬坡与海外厂成本增加压力。","资本开支大幅上调：600 亿–640 亿美元强化设备和上游需求，但压缩短期自由现金流，并提高未来过剩风险。","美国扩产回报仍有不确定性；同时全球半导体仓位高度拥挤，强财报成为兑现和降杠杆窗口，油价与中东冲突又增加宏观折现压力。"]},
  {heading:"全球市场与宏观",paragraphs:["前一交易日道指下跌 0.20%、标普 500 下跌 0.51%、纳指下跌 1.47%；费城半导体指数下跌 4.3%，为连续第二天下跌。","LSEG 数据显示，美国二季度企业盈利增速预期上升至 24.8%，整体盈利并不弱；问题是科技股的市场预期更高。","美国 6 月 CPI 环比下降 0.4%、核心 CPI 同比 2.6%；PPI 环比下降 0.3%。WTI 约 79.25、布伦特约 83.85，绝对水平偏高，7 月能源成本可能在后续通胀数据中重新出现。"]},
  {heading:"AI 与半导体产业链",paragraphs:["晶圆代工：台积电收入与利润创纪录，需求确定性最高；风险转向资本回报和海外成本。设备：ASML 产能指引与台积电资本开支上调进一步验证订单。","GPU：NVDA 合约约跌 4.17%、AMD 跌 7.91%。需求没有直接转弱证据，但高估值和产业链去杠杆正在影响价格。","存储：SKHX -6.34%、SKHY -9.15%、DRAM -9.96%、MU -7.42%、SNDK -13.53%、SMSN -9.31%。网络/定制芯片 MRVL 约跌 11.66%。","Intel 约跌 10.41%。在台积电与 ASML 扩大先进制程能力时，Intel 仍需证明代工客户、良率和资本效率。"]},
  {heading:"机构观点与逆共识",paragraphs:["台积电 CEO 魏哲家表示，AI 相关需求仍极其强劲，预计到 2029、2030 年仍强；客户需求信号支持扩大产能。Counterpoint 的 William Li 认为提高投资对长期增长和满足需求是必要的。","Vital Knowledge 的 Adam Crisafulli 指出，更高资本开支重新引发半导体究竟是周期性还是结构性成长的争论；收入强劲，但利润率压力和部分消费市场疲软是负面因素。","SignatureFD 的 Tony Welch 认为市场乐观情绪很高，任何负面消息都可能打断上涨。Man Group 的 Sumant Wahi 强调 AI 交易已从广泛主题转向战术选股。","逆共识是：资本开支越高，未来自由现金流、折旧和潜在过剩风险越大。台积电强财报后下跌，说明市场正从收入叙事转向资本回报率。"]},
  {heading:"今日观察与策略框架",paragraphs:["台股先观察 43000 点附近承接和台积电 2340–2350 区域，重点看收盘是否脱离日内低点。","美股开盘后重点观察 TSM、NVDA、AMD、MU、SKHY、SNDK 及 SOXX/SMH 成交量。若盈利预期继续上修但估值下跌，可判断为估值压缩；若分析师下调毛利率和自由现金流预期，则需更谨慎。","设备链关注 ASML、Applied Materials、Lam Research、KLA。存储链中期需求仍强，但短期等待 HBM 合同价格、产能分配和正股成交确认。","继续监控油价、美债收益率与美元；三者同步上行时，高估值科技股压力最大。"]}
 ],marketTable:[{symbol:"XYZ100",price:"28650",change:"-3.09%",volume:"6.093 亿美元"},{symbol:"SKHX",price:"1171.9",change:"-6.34%",volume:"6.023 亿美元"},{symbol:"SNDK",price:"1374.1",change:"-13.53%",volume:"4.616 亿美元"},{symbol:"MU",price:"833.55",change:"-7.42%",volume:"3.521 亿美元"},{symbol:"SPCX",price:"126.62",change:"-6.93%",volume:"3.268 亿美元"},{symbol:"DRAM",price:"50.476",change:"-9.96%",volume:"3.200 亿美元"},{symbol:"SKHY",price:"153.35",change:"-9.15%",volume:"2.847 亿美元"},{symbol:"CL",price:"79.246",change:"+0.20%",volume:"2.458 亿美元"},{symbol:"SP500",price:"7472.7",change:"-1.38%",volume:"2.213 亿美元"},{symbol:"SILVER",price:"55.409",change:"-3.20%",volume:"2.161 亿美元"}],sources:[{label:"台积电 2026 年第二季度官方业绩页面",url:"https://investor.tsmc.com/english/quarterly-results/2026/q2"},{label:"Reuters：台积电二季度利润增长 77%",url:"https://www.investing.com/news/stock-market-news/tsmc-q2-profit-jumps-77-to-record-far-surpasses-expectations-4794649"},{label:"AP：台积电新增 1000 亿美元美国投资",url:"https://apnews.com/article/taiwan-tsmc-chipmaking-ai-arizona-fab-ba05b1b952257d371acb9d070e7914ff"},{label:"SEC：台积电 2026 年 6 月营收报告",url:"https://www.sec.gov/Archives/edgar/data/1046179/000104617926000447/tsm-revenue20260713.htm"},{label:"Reuters：全球芯片股下跌",url:"https://sa.marketscreener.com/news/chipmakers-put-pressure-on-equity-indexes-globally-oil-dips-ce7f5ed3dc89f327"},{label:"ASML 二季度业绩",url:"https://www.asml.com/en/investors/financial-results/q2-2026"},{label:"台湾证券交易所即时行情",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"美国 6 月 CPI",url:"https://www.bls.gov/news.release/cpi.htm"},{label:"美国 6 月 PPI",url:"https://www.bls.gov/news.release/archives/ppi_07152026.htm"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"Hyperliquid API 文档",url:"https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint/perpetuals"},{label:"Man Group：半导体交易进入选择阶段",url:"https://www.man.com/insights/views-from-the-floor-2026-14-july"}]},
 {date:"2026-07-16",title:"ASML 确认需求，存储链再度去杠杆",summary:"ASML 二季度收入、毛利率与全年指引全面强劲，确认 AI 设备需求仍在加速；台股等待台积电法说，存储链则再次出现双位数回撤，产业景气与股票交易继续分化。",points:["ASML 二季度收入 93.26 亿欧元、毛利率 54.0%，全年收入指引上调至 430亿–450 亿欧元","台湾加权指数接近平盘，台积电约 2450–2455 新台币，14:00 法说成为核心验证点","SKHX、SKHY、DRAM、MU 与 SNDK 跌约 10%–14%，但 SP500 合约微涨"],risk:"设备订单真实存在，但存储和半导体交易仍高度拥挤。7 月能源冲击尚未进入 6 月通胀数据，且 2027–2028 年设备快速扩产提高了未来供需转向过剩的尾部风险。",sections:[
  {heading:"核心结论",paragraphs:["ASML 确认 AI 设备需求仍在加速。二季度收入 93.26 亿欧元、毛利率 54.0%、净利润 29.18 亿欧元；2026 年收入指引上调至 430 亿–450 亿欧元。2027 年低 NA EUV 与浸没式 DUV 产能均计划增加约 30%。","台股在台积电法说前观望。加权指数接近平盘，台积电约 2450–2455 新台币。真正影响后续估值的是 14:00 公布的毛利率、资本开支、先进封装和海外厂成本指引。","存储链再次双位数回撤。SK 海力士、MU、DRAM、闪迪相关合约普遍跌约 10%–14%，但 SP500 合约微涨，显示主要是高拥挤行业内部去杠杆，并非整个美股系统性风险。","美国通胀连续降温，但 7 月油价仍在 80 美元附近，最新能源冲击尚未进入 6 月 CPI 与 PPI。产业景气与股票交易继续分化，当前优先看盈利和订单兑现。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 45655.52，较前收 45631.59 上涨约 0.05%；盘中区间 44970.64–45713.20。台积电开盘 2430，盘中 2420–2455，前收 2440；盘口约 2450–2455。","法说五项重点是全年美元收入增速、资本开支、2nm/3nm 利用率、CoWoS 扩产，以及海外厂对毛利率的影响。","若资本开支上调且毛利率稳定，设备、代工、先进封装和 HBM 将共同受益；若资本开支上调但毛利率下修，产业链内部回报将进一步分化。"]},
  {heading:"ASML 二季度财报",paragraphs:["二季度总收入 93.26 亿欧元，较一季度 87.67 亿欧元增长；毛利率 54.0%，一季度为 53.0%；净利润 29.18 亿欧元，基本 EPS 7.59 欧元。","装机管理与服务收入 27.62 亿欧元，新光刻系统销量 86 台，一季度为 67 台。三季度指引为收入 110 亿–120 亿欧元、毛利率 55%–57%；全年收入指引 430 亿–450 亿欧元、毛利率 54%–56%。","2027 年低 NA EUV 与浸没式 DUV 产能均计划提高约 30%，并研究 2028 年再提高约 30%。设备龙头正在用产能规划确认客户扩产，但快速增产也提高了未来供需转向过剩的尾部风险。"]},
  {heading:"全球宏观",paragraphs:["美国 6 月总体 CPI 环比 -0.4%，核心 CPI 环比 0.0%、同比 +2.6%。6 月最终需求 PPI 环比 -0.3%；商品下降 1.4%，服务上涨 0.2%。","WTI 约 79.02、布伦特约 83.33 美元。低通胀数据支持科技估值，但 7 月能源冲击仍可能重新影响通胀和政策利率。","Eastspring Investments 首席投资官 Vis Nayar 认为，美伊冲突对亚洲的主要传导渠道是能源价格、汇率和政策利率，台湾与韩国等能源进口经济体尤其敏感。"]},
  {heading:"AI 与半导体产业链",paragraphs:["设备：ASML 收入、毛利率和指引全面强劲。晶圆代工：台积电法说将验证设备需求能否转化为持续利润。","GPU：NVDA 约跌 0.63%，明显强于存储链；AMD 约跌 5.11%。","存储：SKHX -13.90%、SKHY -11.01%、DRAM -11.05%、MU -10.15%、SNDK -11.59%、SMSN -9.05%。中国存储 CXMT 合约逆势上涨约 1.22%，仍需等待公司披露和产能验证。","AMD 继续重点跟踪；TRAM 无足够可靠的主流或官方新增信息，不作为结论依据。"]},
  {heading:"机构观点与逆共识",paragraphs:["ASML CEO Christophe Fouquet 表示，AI 投资正推动先进逻辑和存储需求，客户加速扩产，提高了长期需求可见度。Susquehanna 的 Mehdi Hosseini 在财报前将 ASML 列为重点推荐，实际收入、利润和指引均超预期。","Eastspring CIO Vis Nayar 认为亚洲风险主要经能源价格、汇率和利率传导。Man Group 的 Sumant Wahi 认为 AI 交易已从广泛主题转向战术选股，半导体是高度拥挤区域。","UBS 预计 AI 资本开支 2026 年约 8200 亿美元、2027 年约 9900 亿美元，建议保持配置但提高选择性。","逆共识风险是，ASML 支持 AI 资本开支继续上升，但若云厂商回报或存储价格转弱，2027–2028 年设备快速扩产可能使供应链从短缺转向过剩。"]},
  {heading:"今日观察",paragraphs:["14:00 优先看台积电全年收入、毛利率和资本开支的组合。","美股开盘后观察 ASML 财报涨幅，以及 MU、SKHY、SNDK 跌幅是否小于 TraderXYZ。","继续监控布伦特油价与美债收益率。存储链维持中期积极、短期谨慎，以订单、价格、成交量和期权偏度共同验证。"]}
 ],marketTable:[{symbol:"SKHX",price:"1246.8",change:"-13.90%",volume:"8.557 亿美元"},{symbol:"SKHY",price:"169.6",change:"-11.01%",volume:"5.046 亿美元"},{symbol:"XYZ100",price:"29538",change:"-0.95%",volume:"4.114 亿美元"},{symbol:"SNDK",price:"1586.2",change:"-11.59%",volume:"3.807 亿美元"},{symbol:"DRAM",price:"55.78",change:"-11.05%",volume:"2.575 亿美元"},{symbol:"MU",price:"898.91",change:"-10.15%",volume:"2.487 亿美元"},{symbol:"CL",price:"79.015",change:"-0.21%",volume:"2.402 亿美元"},{symbol:"SPCX",price:"135.77",change:"-1.69%",volume:"1.876 亿美元"},{symbol:"SP500",price:"7576.3",change:"+0.19%",volume:"1.677 亿美元"},{symbol:"BRENTOIL",price:"83.331",change:"-0.95%",volume:"1.432 亿美元"}],sources:[{label:"ASML 二季度业绩",url:"https://www.asml.com/en/investors/financial-results/q2-2026"},{label:"ASML 官方新闻稿",url:"https://ourbrand.asml.com/asset/c8dbf3fc-4c5e-4406-83f6-27694b138245/Press-Release-Financial-Results-Q2-2026.pdf"},{label:"台积电二季度业绩页面",url:"https://investor.tsmc.com/english/quarterly-results/2026/q2"},{label:"台湾证券交易所",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"美国 6 月 PPI",url:"https://www.bls.gov/news.release/archives/ppi_07152026.htm"},{label:"美国 6 月 CPI",url:"https://www.bls.gov/news.release/cpi.htm"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"Reuters：ASML 产能扩张",url:"https://ca.investing.com/news/stock-market-news/asml-capacity-upgrade-soothes-ai-chip-bottleneck-fears-4734995"},{label:"Reuters：亚洲市场能源风险",url:"https://live.euronext.com/en/financial-news/asian-stocks-dip-oil-rises-after-trumps-hormuz-levy-threat"},{label:"UBS：AI 资本开支",url:"https://www.ubs.com/us/en/wealth-management/insights/market-news/article.3534348.html"},{label:"Man Group：半导体选择阶段",url:"https://www.man.com/insights/views-from-the-floor-2026-14-july"}]},
 {date:"2026-07-15",title:"强力修复，但风险尚未解除",summary:"低于预期的美国通胀为风险资产提供缓冲，台股与存储链剧烈反弹；但油价仍处高位，半导体仓位极度拥挤，ASML 与台积电业绩将决定修复能否转为盈利上修。",points:["台湾加权指数反弹约 2.2%，台积电回到 2450 新台币附近","SKHX、SKHY、DRAM、MU 与 SNDK 反弹约 8%–24%，空头回补力量强","6 月核心 CPI 明显降温，但 7 月能源冲击尚未计入，未来 24 小时进入业绩验证窗口"],risk:"强反弹同时包含基本面买盘、空头回补与杠杆清算；存储和全球半导体仍是最拥挤交易之一，必须等待正股成交、ETF 资金流、ASML 订单与台积电指引确认。",sections:[
  {heading:"核心结论",paragraphs:["市场正在进行强力技术修复，但还不能确认风险完全解除。台湾加权指数从昨日大跌中反弹约 2.2%，台积电回到 2450 新台币附近；TraderXYZ 存储链出现 8%–24% 的剧烈反弹。修复幅度说明空头回补和抄底资金很强，也反映波动率仍处高位。","美国 6 月 CPI 环比下降 0.4%，核心 CPI 环比持平、同比 2.6%，均明显降温。这降低了美联储立即转鹰的压力，是风险资产反弹的重要基础。","最新油价冲击尚未进入 6 月 CPI。WTI 和布伦特仍分别约 79.2、84.2 美元。7 月美伊冲突和霍尔木兹海峡风险可能重新推高汽油、运输与生产成本，不能用 6 月低通胀直接外推未来数月。","存储链基本面强，但已成为全球最拥挤交易之一。未来 24 小时的 ASML 二季度结果与 7 月 16 日台积电法说，将决定反弹能否从交易修复转为盈利预期上修。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 45722.81，较前收 44737.95 上涨约 2.20%；盘中区间 44850.69–45801.84。台积电开盘 2425，盘中区间 2415–2460，前收 2420；12:04 盘口约 2450–2455，较前收上涨约 1.2%–1.4%。","指数涨幅大于台积电，说明反弹扩散到其他电子、金融和传统板块，不再完全依赖单一权重股。市场报道台积电二季度营收约 1.27 万亿新台币，同比增长约 36%，上半年营收约 2.4 万亿新台币。","台积电当前更接近“强基本面等待估值确认”。若法说继续上调盈利和产能利用率预期，股价有望维持相对强势；若收入增长强但毛利率、资本开支回报或海外成本不理想，仍可能出现利好兑现。"]},
  {heading:"全球宏观与政策",paragraphs:["美国劳工统计局数据显示，6 月总体 CPI 环比 -0.4%，核心 CPI 环比 0.0%、同比 +2.6%。汽油价格下降是总体通胀回落的重要原因。","这份数据对应 6 月，而当前油价跳升发生在 7 月。政策判断需要同时看已实现的通胀下降与未来能源成本重新上升。WTI 约 79.23、布伦特约 84.17，24 小时涨幅虽收窄，但绝对价格仍高。","若油价停止继续上涨，低核心 CPI 将支持科技股估值修复；若布伦特进一步突破并稳定在更高区域，市场会重新交易通胀、加息和增长放缓风险。"]},
  {heading:"AI 与半导体产业链",paragraphs:["晶圆代工：台积电相对稳健，二季度营收保持高速增长。核心问题转向毛利率、先进封装产能和海外扩张成本。","设备：ASML 将于今天公布二季度结果，重点关注净订单、EUV/High-NA EUV 交付、2026 年收入及 2027 年需求展望。","GPU/加速器：NVDA 合约上涨约 4.38%，AMD 上涨约 3.94%。GPU 链反弹稳健，但弱于最拥挤的存储链，说明资金首先回补前一日跌幅最大的品种。","存储：SKHX +21.33%、SKHY +24.41%、DRAM +11.65%、MU +8.27%、SNDK +8.34%、SMSN +9.55%。SK 海力士管理层预计存储紧张可能延续至 2030 年，并把 2027 年视为供应最紧张阶段之一。"]},
  {heading:"机构观点与逆共识",paragraphs:["UBS 预计 AI 资本开支约为 2026 年 8200 亿美元、2027 年 9900 亿美元，实际数字仍可能更高；半导体估值并非典型泡沫，但资本开支增速放缓会压缩硬件估值。","美国银行基金经理调查显示，“做多全球半导体”仍是最拥挤交易之一。Man Group 的 Sumant Wahi 认为 AI 交易已从广泛主题行情转向更战术化的个股选择。","Coronation 刻意保持较低半导体仓位，主要通过台积电参与，并用保护性看跌期权控制风险。Franklin Templeton/ClearBridge 认为 AI 广度可能延长传统半导体周期，但最终只有具备持续竞争优势的龙头胜出。","逆共识风险是供需强劲已经被拥挤仓位和高估值充分定价。今天 20% 以上的反弹不只代表基本面，也可能是空头回补；越强的短线涨幅，越需要现货成交、盈利上修和订单验证。"]},
  {heading:"今日观察框架",paragraphs:["关注台湾加权指数能否稳定在 45500 上方、台积电能否维持 2450 附近，并观察反弹是否继续扩散。","ASML 结果重点看净订单而非单季收入；净订单更能反映台积电、三星、Intel 等客户未来产能计划。","美股开盘后比较 SKHY、MU、SNDK 与 NVDA、AMD 的相对强弱；若存储链冲高回落而 GPU 链稳定，说明拥挤交易仍在消化。","继续监控美债收益率和布伦特油价。台积电法说后，以盈利预期是否上修作为判断标准，不以单日股价涨跌替代基本面结论。"]}
 ],marketTable:[{symbol:"SKHX",price:"1449.3",change:"+21.33%",volume:"14.445 亿美元"},{symbol:"SKHY",price:"191.46",change:"+24.41%",volume:"4.109 亿美元"},{symbol:"CL",price:"79.225",change:"+0.10%",volume:"3.714 亿美元"},{symbol:"XYZ100",price:"29818",change:"+1.99%",volume:"3.522 亿美元"},{symbol:"DRAM",price:"62.776",change:"+11.65%",volume:"2.902 亿美元"},{symbol:"MU",price:"1002.0",change:"+8.27%",volume:"2.565 亿美元"},{symbol:"BRENTOIL",price:"84.17",change:"+0.49%",volume:"2.551 亿美元"},{symbol:"SP500",price:"7561.3",change:"+0.85%",volume:"2.500 亿美元"},{symbol:"SNDK",price:"1794.9",change:"+8.34%",volume:"2.084 亿美元"},{symbol:"SPCX",price:"138.08",change:"+0.44%",volume:"1.372 亿美元"}],sources:[{label:"美国劳工统计局：2026 年 6 月 CPI",url:"https://www.bls.gov/news.release/cpi.htm?lv=true"},{label:"台积电 2026 年第二季度业绩页面",url:"https://investor.tsmc.com/english/quarterly-results/2026/q2"},{label:"台积电 2026 年月度营收",url:"https://investor.tsmc.com/english/monthly-revenue/2026"},{label:"ASML 2026 年第二季度业绩页面",url:"https://www.asml.com/en/investors/financial-results/q2-2026"},{label:"台湾证券交易所即时行情",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"Hyperliquid API 文档",url:"https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint/perpetuals"},{label:"AP：油价跳涨与 AI 股票下跌",url:"https://apnews.com/article/2d6744b09c68b5473d0bc8584b89e60e"},{label:"UBS：AI 资本开支与半导体选择",url:"https://www.ubs.com/us/en/wealth-management/insights/market-news/article.3534348.html"},{label:"Man Group：半导体交易进入选择阶段",url:"https://www.man.com/insights/views-from-the-floor-2026-14-july"},{label:"Coronation 基金 2026 年 7 月观点",url:"https://www.coronation.com/en-us/institutional/articles/2026/july/Coronation-optimum-growth-usd-fund-july-2026/"},{label:"Franklin Templeton：AI 资本开支能否延长半导体周期",url:"https://www.franklintempleton.com/articles/2026/clearbridge-investments/can-ai-capex-extend-the-semiconductor-cycle"},{label:"台积电上半年营收报道",url:"https://cincodias.elpais.com/companias/2026-07-13/tsmc-el-mayor-productor-mundial-de-chips-registra-unos-ingresos-record-gracias-a-la-demanda-de-la-ia.html"}]},
 {date:"2026-07-14",title:"能源冲击接管市场定价",summary:"美伊冲突与霍尔木兹海峡风险推动油价急升，台股出现系统性去风险，存储链继续成为回撤中心；AI 资本开支仍强，但市场已进入验证现金回报的阶段。",points:["WTI 与布伦特合约分别上涨约 6.85% 和 6.24%，能源冲击压缩科技股估值","台湾加权指数盘中跌约 2.8%，跌幅大于台积电，显示系统性风险释放","SKHX、SNDK、DRAM 与 MRVL 明显承压，7 月 16 日台积电法说成为关键验证点"],risk:"油价、通胀预期和美债收益率正在同步抬升；TraderXYZ 可用于观察风险方向，但仍须以美股正股、ETF 资金流和期权波动率确认精确定价。",sections:[
  {heading:"核心结论",paragraphs:["今天的首要变量已从 AI 需求切换为能源冲击。美伊冲突重新升级、霍尔木兹海峡运输风险上升，周一布伦特一度上涨约 9.6%；截至中午，TraderXYZ 的 WTI 与布伦特仍分别上涨约 6.85% 和 6.24%。油价、通胀预期与美债收益率同步上行，直接压缩高估值科技股的估值空间。","台股出现系统性风险释放，不只是台积电个股问题。台湾加权指数盘中最低约 43654，12:13 约 44115，较前收 45381 下跌约 2.8%；台积电盘中 2390–2430，前收 2440。指数跌幅显著大于台积电，说明其他电子、金融和传统产业也在同步去风险。","存储链仍是本轮回撤中心。SK 海力士相关合约、闪迪、DRAM 与 MRVL 跌幅明显，成交量显著放大。中期供需逻辑尚未被单日行情否定，但短期拥挤度、获利盘与宏观折现率正在共同施压。","AI 资本开支尚未见顶，但股票市场已进入“验证回报”阶段。需求、订单和资本开支可以继续增长，股价却可能因估值过高、资金连续减仓和油价冲击而调整。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 44114.79，较前收 45380.52 下跌约 2.79%；盘中区间 43654.04–45364.40。台积电开盘 2410，盘中区间 2390–2430，前收 2440；按盘口附近 2405–2410 估算，跌幅约 1.2%–1.4%。","台积电占台湾市场权重极高，但今天指数跌幅大于台积电，说明并非单一权重股拖累，而是广泛风险偏好下降。公司将于 7 月 16 日 14:00（台湾时间）举行二季度业绩说明会。","台积电相对大盘仍有一定韧性，但不能把“跌得少”直接等同于调整结束。若油价继续维持高位、利率预期转鹰，即使法说基本面强，估值扩张也会受限。重点应是法说后盈利预期能否继续上修。"]},
  {heading:"全球宏观与政策风险",paragraphs:["Reuters 报道，美伊在周末恢复大规模导弹和无人机交火，伊朗称再次关闭霍尔木兹海峡；美国随后宣布恢复对伊朗港口的海上封锁。AP 报道，周一布伦特上涨约 9.6%至 83.30 美元附近，芯片及 AI 概念股同步下跌，美债收益率随油价走高。","当前担忧的传导路径是：海峡运输受阻 → 原油与 LNG 价格上行 → 通胀重新抬头 → 美联储更难降息 → 长久期科技股估值下压。","本周美国 CPI、PPI 数据将检验能源冲击向物价的传导程度。若通胀高于预期且油价不回落，科技股的宏观压力会进一步增加。"]},
  {heading:"半导体、AI 与上下游",paragraphs:["晶圆代工：台积电盘中跌幅小于大盘，说明资金仍认可先进制程与 AI 代工的相对确定性；7 月 16 日法说将决定这种相对强势能否持续。","GPU/加速器：NVDA 合约约跌 1.98%，AMD 约跌 1.36%，弱于大盘合约但好于部分存储和网络芯片。AI 核心算力需求尚未出现直接反转证据。","存储：SKHX 跌 7.64%、DRAM 跌 3.04%、SKHY 跌 3.64%、SNDK 跌 9.22%；MU 跌幅收窄至约 0.28%–0.63%。资金更集中卖出此前涨幅更大、筹码更拥挤的品种。","网络/定制芯片：MRVL 跌约 6.02%，说明市场在削减数据中心扩建链条中弹性更高、估值更敏感的环节。原油跳涨也提高数据中心电力、运输、化工和设备制造成本。"]},
  {heading:"机构观点与逆共识",paragraphs:["BMO Capital Markets 的 Ian Lyngen 认为，当前全球市场价格主要由霍尔木兹海峡状态驱动，能源板块重新成为市场核心。GLOBALT 的 Thomas Martin 指出，芯片股此前已推动市场达到高位，而当前市场并不便宜，宏观冲击下估值缺少缓冲垫。","摩根士丹利的中期框架仍认为 AI 投资支持美国增长，但能源是最大不确定因素。摩根资管认为 AI 资本开支仍直接利好供应链，不过云厂商资本开支占经营现金流比例已明显上升，未来必须更快证明投资回报。","逆共识风险是：资本开支上行本身可能推高融资需求、能源需求和利率，使供应链盈利增长无法完全转化为股价上涨。今天油价与芯片股的负相关正在验证这一风险。"]},
  {heading:"今日观察与执行框架",paragraphs:["先观察油价能否回落至周一跳涨前区域。油价不回落时，不应仅凭科技股跌幅较大就判断宏观压力已经出清。","台股关注 44000 点附近承接、台积电 2390–2400 区间以及外资净流向；若指数修复但成交缩量，反弹质量有限。","美股开盘后比较存储链与 GPU 链的相对强弱。若 MU、SKHY、SNDK 继续显著弱于 NVDA、AMD，说明市场主要在处理存储拥挤度，而非否定整个 AI 需求。","7 月 16 日台积电法说重点跟踪全年营收增速、资本开支、先进封装产能、2nm/3nm 进展、毛利率及海外厂成本。"]}
 ],marketTable:[{symbol:"SKHX",price:"1178.3",change:"-7.64%",volume:"15.429 亿美元"},{symbol:"CL",price:"79.294",change:"+6.85%",volume:"4.557 亿美元"},{symbol:"XYZ100",price:"29182",change:"-0.97%",volume:"3.761 亿美元"},{symbol:"DRAM",price:"55.602",change:"-3.04%",volume:"2.964 亿美元"},{symbol:"MU",price:"921.37",change:"-0.63%",volume:"2.609 亿美元"},{symbol:"BRENTOIL",price:"83.886",change:"+6.24%",volume:"2.176 亿美元"},{symbol:"SP500",price:"7491.8",change:"-0.53%",volume:"2.151 亿美元"},{symbol:"SKHY",price:"152.93",change:"-3.64%",volume:"2.072 亿美元"},{symbol:"SNDK",price:"1648.1",change:"-9.22%",volume:"2.059 亿美元"},{symbol:"SILVER",price:"57.598",change:"-0.88%",volume:"1.720 亿美元"}],sources:[{label:"台积电 2026 年第二季度业绩页面",url:"https://investor.tsmc.com/english/quarterly-results/2026/q2"},{label:"台积电 2026 年月度营收",url:"https://investor.tsmc.com/english/monthly-revenue/2026"},{label:"台湾证券交易所即时行情",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"Hyperliquid API 文档",url:"https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/info-endpoint/perpetuals"},{label:"Reuters：海湾冲突升级、油价及债券收益率上升",url:"https://au.investing.com/news/commodities-news/shares-slip-in-asia-as-oil-jumps-on-gulf-attacks-4528787"},{label:"Reuters：美股因伊朗局势与芯片股下跌而走弱",url:"https://au.marketscreener.com/news/wall-street-slips-as-iran-tensions-hit-sentiment-chipmakers-drop-ce7f5edcdb88f327"},{label:"AP：油价跳涨、AI 股票下跌",url:"https://apnews.com/article/2d6744b09c68b5473d0bc8584b89e60e"},{label:"Bloomberg：油价续涨、亚洲股市承压",url:"https://www.swissinfo.ch/eng/oil-extends-advance%2C-asian-stocks-set-to-decline%3A-markets-wrap/91740941"},{label:"摩根士丹利 2026 年中展望",url:"https://www.morganstanley.com/Themes/outlooks"},{label:"摩根资管：AI 需求与资本开支",url:"https://am.jpmorgan.com/se/en/asset-management/adv/insights/market-insights/investment-outlook/technology-and-ai/"},{label:"Amundi 2026 年 7 月全球投资观点",url:"https://research-center.amundi.com/article/global-investment-views-july-2026"}]},
 {date:"2026-07-13",title:"台股现货强势，存储链周末降温",summary:"台积电与台湾加权指数维持强势，周末存储链明显回吐、原油走高；AI 资本开支仍在上修，但利率、油价与拥挤筹码正压低估值容错率。",points:["台积电盘中约 2445–2475 新台币，先进制程仍是台股核心支撑","SKHX、DRAM、三星与闪迪相关合约回落约 5%–11%，更像拥挤交易降温","AI 资本开支尚未见顶，但油价、利率和连续减仓成为短线关键变量"],risk:"周末 TraderXYZ 成交集中且规模有限，只适合观察边际情绪；周一仍需用正股成交量、SOXX/SMH 资金流和期权波动率二次确认。",sections:[
  {heading:"核心结论",paragraphs:["台股现货强于周末存储链情绪。台积电盘中区间约 2445–2475 新台币，前收 2415；台湾加权指数约 45696，盘中最高约 46331。先进制程与 AI 代工龙头仍是台湾市场的主要支撑。","周末风险结构是“存储回吐、原油走强”。SK 海力士、DRAM、三星、闪迪相关合约普遍下跌约 5%–11%，而 WTI/布伦特约涨 1.2%。这更像拥挤交易降温与地缘风险溢价回归，不足以单独证明存储基本面反转。","AI 资本开支尚未见顶，但市场开始要求现金回报。机构继续上调云厂商资本开支估计，供应链收入景气仍强，但估值容错率下降。","短线最重要变量不是需求，而是油价、利率和筹码。原油与美债收益率上行会抬高折现率；对冲基金已连续第四周净卖出科技硬件/半导体。"]},
  {heading:"台湾市场与台积电",paragraphs:["台湾加权指数约 45696.59，较前收高约 0.75%；盘中区间 45500.32–46330.91。台积电开盘 2460，盘中区间 2445–2475，前收 2415。由于抓取时最新成交价字段短暂为空，以上以盘口与日内区间为准。","台积电官网在数据截点仍未显示 6 月营收。1–5 月累计营收约 1.962 万亿新台币，同比增长 30.0%。今天的上涨更多是市场对 AI/先进制程景气的定价，尚不是新增月营收数据确认。","中期逻辑仍由先进制程、CoWoS/先进封装与 AI 加速器需求共同支撑；下一步观察月营收、二季度法说、先进封装扩产和主要客户下半年交付指引。"]},
  {heading:"全球宏观与美股主线",paragraphs:["上周美股在芯片股带动下修复，但周末 SP500 合约约跌 0.33%，XYZ100 约跌 0.93%，显示风险偏好略降。WTI 约涨 1.25%，布伦特约涨 1.19%。若油价延续上行，市场会重新评估通胀与降息路径。","摩根士丹利的中期基准情景仍偏建设性，认为 AI 投资支撑增长，同时将能源冲击列为最大宏观变量。Amundi 更谨慎，认为央行转鹰、AI 估值和集中度以及存储股涨幅过快正在压缩容错空间。"]},
  {heading:"半导体、AI 与上下游",paragraphs:["上游设备/晶圆代工：台积电现货走强，先进制程主线仍获资金认可；能源、设备交付及先进封装产能仍是瓶颈。","GPU/加速器：NVDA 约跌 0.21%，明显好于存储链，说明周末抛压集中在此前涨幅更大、交易更拥挤的内存板块。","存储：MU 约跌 3.71%、DRAM 约跌 6.55%、SKHX 约跌 10.56%、SNDK 约跌 5.68%、SMSN 约跌 6.07%。短线是降温信号，中期仍需用 HBM 合同价格、库存、产能利用率与资本开支验证。","网络/定制芯片：MRVL 约跌 2.49%。若云厂商继续上调资本开支，网络互连、光模块、定制 ASIC 与先进封装仍是第二梯队受益方向。"]},
  {heading:"机构观点与逆共识",paragraphs:["摩根士丹利认为 AI 基建资本开支周期仍在加速，同时警告融资需求将增加公司债供给。摩根资管估计五家美国超大规模公司 2026 年资本开支约 6970 亿美元。","高盛主经纪数据显示，对冲基金连续第四周净卖出科技硬件和半导体，并转向指数/ETF、能源与防御板块。Amundi 则主张把风险分散至欧洲、日本、工业、材料和电力基础设施。","即使终端需求没有见顶，芯片股也可能先因利率、估值与拥挤交易而调整。产业景气与股票回报需要分开判断。"]},
  {heading:"今日观察与策略框架",paragraphs:["观察台积电能否在放量情况下维持 2445–2475 区间上方强势，而不只是早盘跳空。","美股开盘重点比较 MU、SK Hynix ADR、SNDK 与 NVDA、AMD 的相对强弱；若存储跌幅快速收窄，周末价格更可能只是低流动性扰动。","同步监控 WTI、10 年期美债收益率和 SOXX/SMH。油价与收益率同步上行时，不宜仅凭产业利好追逐高估值。中期优先选择订单、产能和盈利上修可以验证的环节。"]}
 ],marketTable:[{symbol:"SKHX",price:"1312.2",change:"-10.56%",volume:"3.927 亿美元"},{symbol:"XYZ100",price:"29547",change:"-0.93%",volume:"1.372 亿美元"},{symbol:"CL",price:"74.369",change:"+1.25%",volume:"1.327 亿美元"},{symbol:"SP500",price:"7541.6",change:"-0.33%",volume:"0.891 亿美元"},{symbol:"BRENTOIL",price:"79.098",change:"+1.19%",volume:"0.876 亿美元"},{symbol:"MU",price:"940.88",change:"-3.71%",volume:"0.739 亿美元"},{symbol:"DRAM",price:"58.734",change:"-6.55%",volume:"0.728 亿美元"},{symbol:"SILVER",price:"58.556",change:"-1.99%",volume:"0.541 亿美元"},{symbol:"SKHY",price:"160.92",change:"-6.39%",volume:"0.532 亿美元"},{symbol:"SNDK",price:"1836.8",change:"-5.68%",volume:"0.417 亿美元"}],sources:[{label:"台积电 2026 年月度营收",url:"https://investor.tsmc.com/english/monthly-revenue/2026"},{label:"台积电财务日历",url:"https://investor.tsmc.com/english/financial-calendar"},{label:"台湾证券交易所即时行情",url:"https://mis.twse.com.tw/stock/index.jsp"},{label:"Hyperliquid Info API",url:"https://api.hyperliquid.xyz/info"},{label:"摩根士丹利 2026 年中展望",url:"https://www.morganstanley.com/Themes/outlooks"},{label:"摩根资管：AI 需求与资本开支",url:"https://am.jpmorgan.com/se/en/asset-management/adv/insights/market-insights/investment-outlook/technology-and-ai/"},{label:"Amundi 2026 年 7 月全球投资观点",url:"https://research-center.amundi.com/article/global-investment-views-july-2026"},{label:"Reuters：对冲基金连续减持芯片股",url:"https://www.investing.com/news/stock-market-news/hedge-funds-dumped-chip-stocks-for-a-fourth-week-as-ai-shares-sold-off-4776190"}]},
 {date:"2026-07-10",title:"AI 硬件从防守转向修复",summary:"存储与内存链在高成交中反弹，油价降温缓解科技估值压力。",points:["SKHX、MU、SNDK 与 DRAM 出现高成交修复","AI 资金重新集中到订单与产能可见的瓶颈环节","原油回落，为科技股估值提供喘息空间"],risk:"单日反弹不代表趋势重置，仍需营收、指引与持续成交确认。"},
 {date:"2026-07-09",title:"AI 半导体收窄到龙头",summary:"NVDA 保持强势，TSMC 在关键位下方整理，内存交易继续去拥挤。",points:["NVDA 相对强势，资金更偏向确定性龙头","TSMC 在突破位下方消化筹码","内存链波动加大，拥挤度开始下降"],risk:"龙头强势不等于板块全面扩散，注意高估值资产的回撤风险。"},
 {date:"2026-07-08",title:"AI 半导体进入验证交易",summary:"存储资产选择性修复，市场尚未形成全面风险偏好。",points:["市场从预期交易转向数据和业绩验证","存储链出现选择性反弹而非全面上行","资金继续观察现金市场与永续合约是否共振"],risk:"缺少成交量配合的反弹持续性有限。"},
 {date:"2026-07-07",title:"TSMC 测试关键位，存储永续去风险",summary:"现金市场乐观情绪与存储相关永续合约卖压形成分歧。",points:["TSMC 再次靠近重要突破位置","现金股表现与永续合约资金流出现背离","MU、SKHX 与 DRAM 相关仓位主动降杠杆"],risk:"跨市场背离扩大时，应降低杠杆并等待方向确认。"},
 {date:"2026-07-06",title:"TSM 再次测试突破，MU 防守关键区间",summary:"AI 硬件仍处于防守验证阶段，HYPE 引领加密市场 Beta。",points:["TSM 重新测试前期压力区","MU 在关键区间寻找买盘支撑","HYPE 相对强势，带动加密市场风险偏好"],risk:"硬件链与加密 Beta 尚未完全同步，避免追逐短期波动。"},
 {date:"2026-07-03",title:"硬件链继续洗盘，加密 Beta 回升",summary:"内存和存储链承压，META 商业化预期与 HYPE 推动资金轮动。",points:["内存与存储链在高成交中继续去杠杆","META 的算力商业化叙事吸引资金","HYPE 推动加密市场风险偏好回升"],risk:"资金轮动速度快，强势资产也可能出现剧烈回吐。"},
 {date:"2026-07-02",title:"AI 交易从硬件建设转向算力变现",summary:"META 的算力云计划走强，硬件供应链进入压力测试。",points:["资金从资本开支叙事转向收入兑现","META 算力云计划强化商业化预期","TSM、MU 与设备股面临估值压力测试"],risk:"商业化预期需要订单和利润率验证。"},
 {date:"2026-07-01",title:"半导体获得第二次确认",summary:"TSM、AMD 与设备股确认资本开支广度，MU 消化涨幅。",points:["TSM 与 AMD 延续强势确认","设备股同步走强，资本开支广度改善","MU 高位整理，等待下一轮催化"],risk:"板块确认后仍要观察成交是否持续，防止假突破。"},
 {date:"2026-06-29",title:"AI 内存趋势仍在，MU 等待二次确认",summary:"MU 保持高流量，台湾市场 TSM 反弹，宏观数据限制估值扩张。",points:["MU 仍是内存链主要资金焦点","台湾现金市场推动 TSM 修复","通胀数据限制科技股估值扩张"],risk:"宏观利率重新上行可能压制高估值半导体。"},
 {date:"2026-06-01",title:"AI 硬件维持强势",summary:"台湾现金市场确认 TSM，HYPE 支撑风险偏好。",points:["台湾现金市场确认 TSM 买盘","AI 硬件主线保持相对强势","HYPE 为加密风险偏好提供支撑"],risk:"高位趋势中应关注量价背离与拥挤度。"},
 {date:"2026-05-30",title:"半导体高位轮动",summary:"MU 受益于 HBM 主题，TSM 与 NVDA 降温，HYPE 维持强势。",points:["MU 继续受益于 HBM 需求叙事","TSM 与 NVDA 高位降温","HYPE 在加密资产中保持相对强势"],risk:"高位轮动不等于风险消失，注意龙头补跌。"},
 {date:"2026-05-29",title:"AI 半导体进入高位分化",summary:"TSM 与 NVDA 上涨，MU 高位换手。",points:["TSM 延续现金市场强势","NVDA 保持 AI 核心资产地位","MU 高位成交放大、筹码换手"],risk:"分化阶段追高胜率下降，应等待明确支撑位。"},
 {date:"2026-05-28",title:"资金转向确定性",summary:"TSM 与 MU 领涨，NVDA 短线降温。",points:["资金偏好订单更清晰的供应链资产","TSM 与 MU 成为当日主要强势标的","NVDA 短线降温但核心叙事未变"],risk:"确定性交易拥挤后，同样可能出现快速估值收缩。"}
];
export const getBrief=(date:string)=>briefs.find(x=>x.date===date);
